
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.1.0.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace TerminalGuiDesigner.UI.Windows {
    using System;
    using Terminal.Gui;
    using System.Collections;
    using System.Collections.Generic;
    
    
    public partial class ArrayEditor : Terminal.Gui.Dialog {
        
        private Terminal.Gui.FrameView frameView;
        
        private Terminal.Gui.ListView lvElements;
        
        private Terminal.Gui.Button btnAddElement;
        
        private Terminal.Gui.Button btnDelete;
        
        private Terminal.Gui.Button btnMoveUp;
        
        private Terminal.Gui.Button btnMoveDown;
        
        private Terminal.Gui.Button btnEdit;
        
        private Terminal.Gui.LineView lineView;
        
        private Terminal.Gui.Button btnOk;
        
        private Terminal.Gui.Button btnCancel;
        
        private void InitializeComponent() {
            this.btnCancel = new Terminal.Gui.Button();
            this.btnOk = new Terminal.Gui.Button();
            this.lineView = new Terminal.Gui.LineView();
            this.btnEdit = new Terminal.Gui.Button();
            this.btnMoveDown = new Terminal.Gui.Button();
            this.btnMoveUp = new Terminal.Gui.Button();
            this.btnDelete = new Terminal.Gui.Button();
            this.btnAddElement = new Terminal.Gui.Button();
            this.lvElements = new Terminal.Gui.ListView();
            this.frameView = new Terminal.Gui.FrameView();
            this.Width = Dim.Percent(85);
            this.Height = Dim.Percent(85);
            this.X = Pos.Center();
            this.Y = Pos.Center();
            this.Visible = true;
            this.Modal = true;
            this.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Title = "Array Editor";
            this.frameView.Width = Dim.Fill(0);
            this.frameView.Height = Dim.Fill(3);
            this.frameView.X = 0;
            this.frameView.Y = 0;
            this.frameView.Visible = true;
            this.frameView.Data = "frameView";
            this.frameView.TextAlignment = Terminal.Gui.Alignment.Start;
            this.frameView.Title = "Elements";
            this.Add(this.frameView);
            this.lvElements.Width = Dim.Fill(0);
            this.lvElements.Height = Dim.Fill(0);
            this.lvElements.X = 1;
            this.lvElements.Y = 0;
            this.lvElements.Visible = true;
            this.lvElements.Data = "lvElements";
            this.lvElements.TextAlignment = Terminal.Gui.Alignment.Start;
            this.lvElements.Source = new Terminal.Gui.ListWrapper(new string[] {
                        "Item1",
                        "Item2",
                        "Item3"});
            this.lvElements.AllowsMarking = false;
            this.lvElements.AllowsMultipleSelection = true;
            this.frameView.Add(this.lvElements);
            this.btnAddElement.Width = 8;
            this.btnAddElement.Height = 1;
            this.btnAddElement.X = 1;
            this.btnAddElement.Y = Pos.AnchorEnd(3);
            this.btnAddElement.Visible = true;
            this.btnAddElement.Data = "btnAddElement";
            this.btnAddElement.Text = "Add";
            this.btnAddElement.TextAlignment = Terminal.Gui.Alignment.Center;
            this.btnAddElement.IsDefault = false;
            this.Add(this.btnAddElement);
            this.btnDelete.Width = 8;
            this.btnDelete.Height = 1;
            this.btnDelete.X = 9;
            this.btnDelete.Y = Pos.AnchorEnd(3);
            this.btnDelete.Visible = true;
            this.btnDelete.Data = "btnDelete";
            this.btnDelete.Text = "Delete";
            this.btnDelete.TextAlignment = Terminal.Gui.Alignment.Center;
            this.btnDelete.IsDefault = false;
            this.Add(this.btnDelete);
            this.btnMoveUp.Width = 8;
            this.btnMoveUp.Height = 1;
            this.btnMoveUp.X = 20;
            this.btnMoveUp.Y = Pos.AnchorEnd(3);
            this.btnMoveUp.Visible = true;
            this.btnMoveUp.Data = "btnMoveUp";
            this.btnMoveUp.Text = "Move Up";
            this.btnMoveUp.TextAlignment = Terminal.Gui.Alignment.Center;
            this.btnMoveUp.IsDefault = false;
            this.Add(this.btnMoveUp);
            this.btnMoveDown.Width = 8;
            this.btnMoveDown.Height = 1;
            this.btnMoveDown.X = 32;
            this.btnMoveDown.Y = Pos.AnchorEnd(3);
            this.btnMoveDown.Visible = true;
            this.btnMoveDown.Data = "btnMoveDown";
            this.btnMoveDown.Text = "Move Down";
            this.btnMoveDown.TextAlignment = Terminal.Gui.Alignment.Center;
            this.btnMoveDown.IsDefault = false;
            this.Add(this.btnMoveDown);
            this.btnEdit.Width = 8;
            this.btnEdit.Height = 1;
            this.btnEdit.X = 46;
            this.btnEdit.Y = Pos.AnchorEnd(3);
            this.btnEdit.Visible = true;
            this.btnEdit.Data = "btnEdit";
            this.btnEdit.Text = "Edit";
            this.btnEdit.TextAlignment = Terminal.Gui.Alignment.Center;
            this.btnEdit.IsDefault = false;
            this.Add(this.btnEdit);
            this.lineView.Width = Dim.Fill(1);
            this.lineView.Height = 1;
            this.lineView.X = -1;
            this.lineView.Y = Pos.AnchorEnd(2);
            this.lineView.Visible = true;
            this.lineView.Data = "lineView";
            this.lineView.TextAlignment = Terminal.Gui.Alignment.Start;
            this.lineView.LineRune = new System.Text.Rune('─');
            this.lineView.Orientation = Terminal.Gui.Orientation.Horizontal;
            this.Add(this.lineView);
            this.btnOk.Width = 8;
            this.btnOk.Height = 1;
            this.btnOk.X = 0;
            this.btnOk.Y = Pos.AnchorEnd(1);
            this.btnOk.Visible = true;
            this.btnOk.Data = "btnOk";
            this.btnOk.Text = "Ok";
            this.btnOk.TextAlignment = Terminal.Gui.Alignment.Center;
            this.btnOk.IsDefault = false;
            this.Add(this.btnOk);
            this.btnCancel.Width = 8;
            this.btnCancel.Height = 1;
            this.btnCancel.X = 9;
            this.btnCancel.Y = Pos.AnchorEnd(1);
            this.btnCancel.Visible = true;
            this.btnCancel.Data = "btnCancel";
            this.btnCancel.Text = "Cancel";
            this.btnCancel.TextAlignment = Terminal.Gui.Alignment.Center;
            this.btnCancel.IsDefault = false;
            this.Add(this.btnCancel);
        }
    }
}
