
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.1.0.0
//      You can make changes to this file and they will not be overwritten when saving.
//  </auto-generated>
// -----------------------------------------------------------------------------

using System.Collections.ObjectModel;
using JetBrains.Annotations;
using Terminal.Gui.App;
using Terminal.Gui.Input;

namespace TerminalGuiDesigner.UI.Windows {
    using System.Collections;
    using Terminal.Gui;
    using TerminalGuiDesigner.ToCode;

    /// <summary>
    /// UI for configuring array elements
    /// </summary>
    public partial class ArrayEditor : IValueGetterDialog {

        /// <summary>
        /// True if the editing was aborted.
        /// </summary>
        public bool Cancelled { get; private set; } = true;

        private readonly IApplication app;
        private readonly Design design;
        private Type elementType;

        /// <summary>
        /// The new array 
        /// </summary>
        public object ActualResult => ResultAsList;

        /// <summary>
        /// Returns the <see cref="Array"/> being designed as an <see cref="IList"/>
        /// </summary>
        public IList ResultAsList { get; private set; }


        /// <summary>
        /// Creates a new instance of the editor configured to build lists of <paramref name="elementType"/>
        /// and showing initial values held in <paramref name="oldValue"/> (if any).
        /// </summary>
        /// <param name="app"></param>
        /// <param name="design"></param>
        /// <param name="elementType"></param>
        /// <param name="oldValue"></param>
        public ArrayEditor(IApplication app, Design design, Type elementType, IList oldValue) {
            InitializeComponent();
            this.app = app;
            this.design = design;
            this.elementType = elementType;
            
            Type listType = typeof(List<>).MakeGenericType(elementType);
            ResultAsList = (IList)Activator.CreateInstance(listType);
         
            foreach(var e in oldValue)
            {
                ResultAsList.Add(e);
            }

            lvElements.Source = ResultAsList.ToListDataSource();
            lvElements.KeyDown += LvElements_KeyDown;
            lvElements.MouseEvent += LvElements_MouseEvent;
            btnOk.Accepting += BtnOk_Clicked;
            btnCancel.Accepting += BtnCancel_Clicked;
            btnAddElement.Accepting += BtnAddElement_Clicked;
            btnDelete.Accepting +=  DeleteSelectedItem_Clicked;
            btnMoveDown.Accepting += BtnMoveDown_Clicked;
            btnMoveUp.Accepting += BtnMoveUp_Clicked;
            btnEdit.Accepting += BtnEdit_Clicked;
        }

        private void LvElements_MouseEvent(object sender, Mouse e)
        {
            if(e.IsDoubleClicked)
            {
                EditSelectedItem();
                e.Handled = true;
            }
        }

        private void BtnMoveUp_Clicked(object sender, CommandEventArgs e)
        {
            // Moving up means reducing the index by 1
            var idx = lvElements.SelectedItem ?? -1;

            if (idx >= 1 && idx < ResultAsList.Count)
            { 
                var toMove = ResultAsList[idx];
                var newIndex = idx - 1;
                ResultAsList.RemoveAt(idx);
                ResultAsList.Insert(newIndex, toMove);

                lvElements.Source = ResultAsList.ToListDataSource();
                lvElements.SelectedItem = newIndex;
                lvElements.SetNeedsDraw();
            }

            e.Handled = true;
        }

        private void BtnMoveDown_Clicked(object sender, CommandEventArgs e)
        {
            // Moving up means increasing the index by 1
            var idx = lvElements.SelectedItem ?? -1;

            if (idx >= 0 && idx < ResultAsList.Count-1)
            {
                var toMove = ResultAsList[idx];
                var newIndex = idx + 1;
                ResultAsList.RemoveAt(idx);
                ResultAsList.Insert(newIndex, toMove);

                lvElements.Source = ResultAsList.ToListDataSource();
                lvElements.SelectedItem = newIndex;
                lvElements.SetNeedsDraw();
            }

            e.Handled = true;
        }

        private void LvElements_KeyDown(object sender, Key e)
        {
            if(e == Key.DeleteChar)
            {
                DeleteSelectedItem();
                e.Handled = true;
            }

            if(e == Key.Enter)
            {
                EditSelectedItem();
                e.Handled = true;
            }
        }

        private void DeleteSelectedItem_Clicked(object sender, CommandEventArgs e)
        {
            e.Handled = true;
            DeleteSelectedItem();
        }


        private void DeleteSelectedItem()
        {
            var idx = lvElements.SelectedItem??-1;

            if (idx >= 0 && idx < ResultAsList.Count)
            {
                ResultAsList.RemoveAt(idx);

                lvElements.Source = ResultAsList.ToListDataSource();
                lvElements.SetNeedsDraw();
                if(ResultAsList.Count>=1)
                {
                    lvElements.SelectedItem = 0;
                }
            }
        }

        private void BtnAddElement_Clicked(object sender, CommandEventArgs e)
        {
            if(ValueFactory.GetNewValue(app, "Element Value", design, this.elementType,null, out var newValue,true))
            {
                ResultAsList.Add(newValue);                
            }

            lvElements.Source = ResultAsList.ToListDataSource();
            lvElements.SelectedItem = ResultAsList.Count - 1;
            lvElements.SetNeedsDraw();
            e.Handled = true;
        }

        private void BtnEdit_Clicked(object sender, CommandEventArgs e)
        {
            EditSelectedItem();
            e.Handled = true;
        }

        private void EditSelectedItem()
        {
            var idx = lvElements.SelectedItem ?? -1;

            if (idx >= 0 && idx < ResultAsList.Count)
            {
                var toEdit = ResultAsList[idx];

                if (ValueFactory.GetNewValue(app, "Element Value", design, this.elementType, toEdit, out var newValue, true))
                {
                    // Replace old with new
                    ResultAsList.RemoveAt(idx);
                    ResultAsList.Insert(idx, newValue);
                }

                lvElements.Source = ResultAsList.ToListDataSource();
                lvElements.SelectedItem = idx;
                lvElements.SetNeedsDraw();
            }
        }

        private void BtnCancel_Clicked(object sender, CommandEventArgs e)
        {
            e.Handled = true;
            Cancelled = true;
            app.RequestStop();
        }

        private void BtnOk_Clicked(object sender, CommandEventArgs e)
        {
            e.Handled = true;
            Cancelled = false;
            app.RequestStop();
        }
    }
}
