
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v2.0.0.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace TerminalGuiDesigner.UI.Windows {
    using System;
    using Terminal.Gui;
    using Terminal.Gui.App;
    using Terminal.Gui.Drawing;
    using Terminal.Gui.Input;
    using Terminal.Gui.ViewBase;
    using Terminal.Gui.Views;
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Drawing;
    
    
    public partial class ArrayEditor : Terminal.Gui.Views.Dialog {
        
        private Terminal.Gui.Views.FrameView frameView;
        
        private Terminal.Gui.Views.ListView lvElements;
        
        private Terminal.Gui.Views.Button btnAddElement;
        
        private Terminal.Gui.Views.Button btnDelete;
        
        private Terminal.Gui.Views.Button btnMoveUp;
        
        private Terminal.Gui.Views.Button btnMoveDown;
        
        private Terminal.Gui.Views.Button btnEdit;
        
        private Terminal.Gui.Views.Line Line;
        
        private Terminal.Gui.Views.Button btnOk;
        
        private Terminal.Gui.Views.Button btnCancel;
        
        private void InitializeComponent() {
            this.btnCancel = new Terminal.Gui.Views.Button();
            this.btnOk = new Terminal.Gui.Views.Button();
            this.Line = new Terminal.Gui.Views.Line();
            this.btnEdit = new Terminal.Gui.Views.Button();
            this.btnMoveDown = new Terminal.Gui.Views.Button();
            this.btnMoveUp = new Terminal.Gui.Views.Button();
            this.btnDelete = new Terminal.Gui.Views.Button();
            this.btnAddElement = new Terminal.Gui.Views.Button();
            this.lvElements = new Terminal.Gui.Views.ListView();
            this.frameView = new Terminal.Gui.Views.FrameView();
            this.Width = Dim.Percent(85);
            this.Height = Dim.Percent(85);
            this.X = Pos.Center();
            this.Y = Pos.Center();
            this.Visible = true;
            this.Arrangement = (Terminal.Gui.ViewBase.ViewArrangement.Movable | Terminal.Gui.ViewBase.ViewArrangement.Overlapped);
            this.CanFocus = true;
            this.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyle.Transparent;
            this.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Title = "Array Editor";
            this.frameView.Width = Dim.Fill(0);
            this.frameView.Height = Dim.Fill(5);
            this.frameView.X = 0;
            this.frameView.Y = 0;
            this.frameView.Visible = true;
            this.frameView.Arrangement = Terminal.Gui.ViewBase.ViewArrangement.Fixed;
            this.frameView.CanFocus = true;
            this.frameView.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyle.None;
            this.frameView.Data = "frameView";
            this.frameView.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.frameView.Title = "Elements";
            this.Add(this.frameView);
            this.lvElements.Width = Dim.Fill(0);
            this.lvElements.Height = Dim.Fill(0);
            this.lvElements.X = 1;
            this.lvElements.Y = 0;
            this.lvElements.Visible = true;
            this.lvElements.Arrangement = Terminal.Gui.ViewBase.ViewArrangement.Fixed;
            this.lvElements.CanFocus = true;
            this.lvElements.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyle.None;
            this.lvElements.Data = "lvElements";
            this.lvElements.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.lvElements.Source = new Terminal.Gui.Views.ListWrapper<string>(new System.Collections.ObjectModel.ObservableCollection<string>(new string[] {
                            "Item1",
                            "Item2",
                            "Item3"}));
            this.frameView.Add(this.lvElements);
            this.btnAddElement.Width = Dim.Auto();
            this.btnAddElement.Height = Dim.Auto();
            this.btnAddElement.X = 1;
            this.btnAddElement.Y = Pos.AnchorEnd(5);
            this.btnAddElement.Visible = true;
            this.btnAddElement.Arrangement = Terminal.Gui.ViewBase.ViewArrangement.Fixed;
            this.btnAddElement.CanFocus = true;
            this.btnAddElement.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyle.Opaque;
            this.btnAddElement.Data = "btnAddElement";
            this.btnAddElement.Text = "Add";
            this.btnAddElement.TextAlignment = Terminal.Gui.ViewBase.Alignment.Center;
            this.btnAddElement.IsDefault = false;
            this.Add(this.btnAddElement);
            this.btnDelete.Width = Dim.Auto();
            this.btnDelete.Height = Dim.Auto();
            this.btnDelete.X = 9;
            this.btnDelete.Y = Pos.AnchorEnd(5);
            this.btnDelete.Visible = true;
            this.btnDelete.Arrangement = Terminal.Gui.ViewBase.ViewArrangement.Fixed;
            this.btnDelete.CanFocus = true;
            this.btnDelete.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyle.Opaque;
            this.btnDelete.Data = "btnDelete";
            this.btnDelete.Text = "Delete";
            this.btnDelete.TextAlignment = Terminal.Gui.ViewBase.Alignment.Center;
            this.btnDelete.IsDefault = false;
            this.Add(this.btnDelete);
            this.btnMoveUp.Width = Dim.Auto();
            this.btnMoveUp.Height = Dim.Auto();
            this.btnMoveUp.X = 22;
            this.btnMoveUp.Y = Pos.AnchorEnd(5);
            this.btnMoveUp.Visible = true;
            this.btnMoveUp.Arrangement = Terminal.Gui.ViewBase.ViewArrangement.Fixed;
            this.btnMoveUp.CanFocus = true;
            this.btnMoveUp.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyle.Opaque;
            this.btnMoveUp.Data = "btnMoveUp";
            this.btnMoveUp.Text = "Move Up";
            this.btnMoveUp.TextAlignment = Terminal.Gui.ViewBase.Alignment.Center;
            this.btnMoveUp.IsDefault = false;
            this.Add(this.btnMoveUp);
            this.btnMoveDown.Width = Dim.Auto();
            this.btnMoveDown.Height = Dim.Auto();
            this.btnMoveDown.X = 34;
            this.btnMoveDown.Y = Pos.AnchorEnd(5);
            this.btnMoveDown.Visible = true;
            this.btnMoveDown.Arrangement = Terminal.Gui.ViewBase.ViewArrangement.Fixed;
            this.btnMoveDown.CanFocus = true;
            this.btnMoveDown.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyle.Opaque;
            this.btnMoveDown.Data = "btnMoveDown";
            this.btnMoveDown.Text = "Move Down";
            this.btnMoveDown.TextAlignment = Terminal.Gui.ViewBase.Alignment.Center;
            this.btnMoveDown.IsDefault = false;
            this.Add(this.btnMoveDown);
            this.btnEdit.Width = Dim.Auto();
            this.btnEdit.Height = Dim.Auto();
            this.btnEdit.X = 48;
            this.btnEdit.Y = Pos.AnchorEnd(5);
            this.btnEdit.Visible = true;
            this.btnEdit.Arrangement = Terminal.Gui.ViewBase.ViewArrangement.Fixed;
            this.btnEdit.CanFocus = true;
            this.btnEdit.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyle.Opaque;
            this.btnEdit.Data = "btnEdit";
            this.btnEdit.Text = "Edit";
            this.btnEdit.TextAlignment = Terminal.Gui.ViewBase.Alignment.Center;
            this.btnEdit.IsDefault = false;
            this.Add(this.btnEdit);
            this.Line.Width = Dim.Fill(1);
            this.Line.Height = 1;
            this.Line.X = -1;
            this.Line.Y = Pos.AnchorEnd(3);
            this.Line.Visible = true;
            this.Line.Arrangement = Terminal.Gui.ViewBase.ViewArrangement.Fixed;
            this.Line.CanFocus = true;
            this.Line.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyle.None;
            this.Line.Data = "Line";
            this.Line.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start; 
            this.Line.Orientation = Terminal.Gui.ViewBase.Orientation.Horizontal;
            this.Add(this.Line);
            this.btnOk.Width = Dim.Auto();
            this.btnOk.Height = Dim.Auto();
            this.btnOk.X = 0;
            this.btnOk.Y = Pos.AnchorEnd(2);
            this.btnOk.Visible = true;
            this.btnOk.Arrangement = Terminal.Gui.ViewBase.ViewArrangement.Fixed;
            this.btnOk.CanFocus = true;
            this.btnOk.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyle.Opaque;
            this.btnOk.Data = "btnOk";
            this.btnOk.Text = "Ok";
            this.btnOk.TextAlignment = Terminal.Gui.ViewBase.Alignment.Center;
            this.btnOk.IsDefault = false;
            this.Add(this.btnOk);
            this.btnCancel.Width = Dim.Auto();
            this.btnCancel.Height = Dim.Auto();
            this.btnCancel.X = 7;
            this.btnCancel.Y = Pos.AnchorEnd(2);
            this.btnCancel.Visible = true;
            this.btnCancel.Arrangement = Terminal.Gui.ViewBase.ViewArrangement.Fixed;
            this.btnCancel.CanFocus = true;
            this.btnCancel.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyle.Opaque;
            this.btnCancel.Data = "btnCancel";
            this.btnCancel.Text = "Cancel";
            this.btnCancel.TextAlignment = Terminal.Gui.ViewBase.Alignment.Center;
            this.btnCancel.IsDefault = false;
            this.Add(this.btnCancel);
        }
    }
}
