
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.15.0
//      You can make changes to this file and they will not be overwritten when saving.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace TerminalGuiDesigner.UI.Windows {
    using System;
    using Terminal.Gui;
    
    
    public partial class ColorSchemeEditor {
        
        ColorScheme Result {get;}
        public bool Cancelled { get; set; } = true;

        public ColorSchemeEditor(ColorScheme scheme) {
            InitializeComponent();

            Result = scheme;

            SetColorPatches();

            btnEditNormal.Clicked += ()=>{
                Result.Normal = PickNewColorsFor(Result.Normal);
                SetColorPatches();
                };
            
        }

        private Terminal.Gui.Attribute PickNewColorsFor(Terminal.Gui.Attribute current)
        {
            var pick = new ColorPicker(current);
            Application.Run(pick);

            return pick.Cancelled ? current : pick.Result ?? current;
        }

        private void SetColorPatches()
        {
            SetColor(lblBackgroundNormal,Result.Normal.Background);
            SetColor(lblForegroundNormal,Result.Normal.Foreground);
        }

        private void SetColor(Label label, Color color)
        {
            label.ColorScheme = new ColorScheme{Normal = new Terminal.Gui.Attribute(color,color)};
        }
    }
}
