
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.15.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace TerminalGuiDesigner.UI.Windows {
    using System;
    using Terminal.Gui;
    
    using ColorPicker = TerminalGuiDesigner.UI.Windows.ColorPicker;
    
    public partial class ColorSchemeEditor : Terminal.Gui.Dialog {
        
        private Terminal.Gui.Label label2;
        
        private Terminal.Gui.Label lblForegroundNormal;
        
        private Terminal.Gui.Label label1;
        
        private Terminal.Gui.Label lblBackgroundNormal;
        
        private Terminal.Gui.Button btnEditNormal;
        
        private Terminal.Gui.Button btnOk;
        
        private Terminal.Gui.Button btnDeleteScheme;
        
        private Terminal.Gui.Button btnCancel;
        
        private void InitializeComponent() {
            this.Width = Dim.Percent(85f);
            this.Height = Dim.Percent(85f);
            this.X = Pos.Center();
            this.Y = Pos.Center();
            this.Modal = true;
            this.Text = "";
            this.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.Border.BorderBrush = Terminal.Gui.Color.Blue;
            this.Border.Effect3D = true;
            this.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Title = "Color Scheme Editor";
            this.label2 = new Terminal.Gui.Label();
            this.label2.Width = 7;
            this.label2.Height = 1;
            this.label2.X = 0;
            this.label2.Y = 0;
            this.label2.Data = "label2";
            this.label2.Text = "Normal:";
            this.label2.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label2);
            this.lblForegroundNormal = new Terminal.Gui.Label();
            this.lblForegroundNormal.Width = 1;
            this.lblForegroundNormal.Height = 1;
            this.lblForegroundNormal.X = Pos.Right(label2) + 1;
            this.lblForegroundNormal.Y = 0;
            this.lblForegroundNormal.Data = "lblForegroundNormal";
            this.lblForegroundNormal.Text = "";
            this.lblForegroundNormal.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.lblForegroundNormal);
            this.label1 = new Terminal.Gui.Label();
            this.label1.Width = 1;
            this.label1.Height = 1;
            this.label1.X = 9;
            this.label1.Y = 0;
            this.label1.Data = "label1";
            this.label1.Text = "\\";
            this.label1.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label1);
            this.lblBackgroundNormal = new Terminal.Gui.Label();
            this.lblBackgroundNormal.Width = 1;
            this.lblBackgroundNormal.Height = 1;
            this.lblBackgroundNormal.X = Pos.Right(label2) + 3;
            this.lblBackgroundNormal.Y = 0;
            this.lblBackgroundNormal.Data = "lblBackgroundNormal";
            this.lblBackgroundNormal.Text = "";
            this.lblBackgroundNormal.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.lblBackgroundNormal);
            this.btnEditNormal = new Terminal.Gui.Button();
            this.btnEditNormal.Width = 13;
            this.btnEditNormal.X = 12;
            this.btnEditNormal.Y = 0;
            this.btnEditNormal.Data = "btnEditNormal";
            this.btnEditNormal.Text = "Choose...";
            this.btnEditNormal.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.btnEditNormal.IsDefault = false;
            this.Add(this.btnEditNormal);
            this.btnOk = new Terminal.Gui.Button();
            this.btnOk.Width = 6;
            this.btnOk.X = 4;
            this.btnOk.Y = 6;
            this.btnOk.Data = "btnOk";
            this.btnOk.Text = "Ok";
            this.btnOk.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.btnOk.IsDefault = false;
            this.Add(this.btnOk);
            this.btnDeleteScheme = new Terminal.Gui.Button();
            this.btnDeleteScheme.Width = 17;
            this.btnDeleteScheme.X = 11;
            this.btnDeleteScheme.Y = 6;
            this.btnDeleteScheme.Data = "btnDeleteScheme";
            this.btnDeleteScheme.Text = "Delete Scheme";
            this.btnDeleteScheme.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.btnDeleteScheme.IsDefault = false;
            this.Add(this.btnDeleteScheme);
            this.btnCancel = new Terminal.Gui.Button();
            this.btnCancel.Width = 10;
            this.btnCancel.X = 29;
            this.btnCancel.Y = 6;
            this.btnCancel.Data = "btnCancel";
            this.btnCancel.Text = "Cancel";
            this.btnCancel.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.btnCancel.IsDefault = false;
            this.Add(this.btnCancel);
        }
    }
}
