
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.15.0
//      You can make changes to this file and they will not be overwritten when saving.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace TerminalGuiDesigner.UI.Windows {
    using System;
    using System.Collections.Generic;
    using System.Data;
    using Terminal.Gui;
    using static TerminalGuiDesigner.ColorSchemeManager;

    public partial class ColorSchemesUI {
        const string NameColumn = "Name";
        const string EditColumnName = " ";
        const string DeleteColumnName = "  ";

        public Design Design { get; }

        private NamedColorScheme[] _schemes;

        public ColorSchemesUI(Design design) {
            
            InitializeComponent();

            Design = design;

            tvColorSchemes.NullSymbol = " ";

            var tbl = tvColorSchemes.Table;

            foreach(DataColumn col in tbl.Columns)
            {
                col.DataType = typeof(int);
            }

            var sName = tvColorSchemes.Style.GetOrCreateColumnStyle(tbl.Columns[NameColumn]);
            sName.RepresentationGetter = GetName;

            var sEdit = tvColorSchemes.Style.GetOrCreateColumnStyle(tbl.Columns[EditColumnName]);
            sEdit.RepresentationGetter = GetEditString;
            sEdit.MinWidth = 7;
            
            var sDelete = tvColorSchemes.Style.GetOrCreateColumnStyle(tbl.Columns[DeleteColumnName]);
            sDelete.RepresentationGetter = GetDeleteString;
            sDelete.MinWidth = 8;

            tvColorSchemes.CellActivated += CellActivated;

            SetupSwatchColumn(tbl,tbl.Columns["0"],(s)=>s?.Normal.Foreground ?? tvColorSchemes.ColorScheme.Normal.Background);

            BuildDataTableRows();
        }

        private void SetupSwatchColumn(DataTable tbl, DataColumn dataColumn, Func<ColorScheme, Color> value)
        {
            //TODO: Set cell color delegate and Representation
        }

        private void CellActivated(TableView.CellActivatedEventArgs e)
        {
            var col = e.Table.Columns[e.Col];
            var val = (int)e.Table.Rows[e.Row][e.Col];

            if(col.ColumnName == EditColumnName && val < _schemes.Length)
            {
                var edit = new ColorSchemeEditor(_schemes[val].Scheme);
                Application.Run(edit);

                ColorSchemeManager.Instance.AddOrUpdateScheme(_schemes[val].Name,edit.Result);
                BuildDataTableRows();
            }

            if(col.ColumnName == NameColumn)
            {
                var oldName = GetName(val);
                if(Modals.GetString("Rename Color Scheme","Name",oldName,out var newName) && !string.IsNullOrWhiteSpace(newName))
                {
                    ColorSchemeManager.Instance.RenameScheme(oldName,Design.GetUniqueFieldName(newName));
                }
            }

            if(col.ColumnName == DeleteColumnName)
            {
                // actually its the [+] button
                if(val == int.MaxValue)
                {
                    ColorSchemeManager.Instance.AddOrUpdateScheme(GetNewColorName(),new ColorScheme());
                    BuildDataTableRows();
                    tvColorSchemes.SelectedRow++;
                }
            }
        }

        private string GetNewColorName()
        {  
            return Design.GetUniqueFieldName("scheme");
        }

        private string GetDeleteString(object arg)
        {
            return (int)arg == int.MaxValue ? "[New]" : "[Delete]";
        }

        private string GetEditString(object arg)
        {
            return (int)arg == int.MaxValue ? "" : "[ Edit ]";
        }

        private string GetName(object arg)
        {
            if(arg is int i && i <_schemes.Length)
            {
                return _schemes[i].Name;
            }
            return "";
        }

        private void BuildDataTableRows()
        {
            var tbl = tvColorSchemes.Table;
            tbl.Rows.Clear();

            _schemes = ColorSchemeManager.Instance.Schemes.ToArray();

            for(int i = 0 ; i < _schemes.Length;i++)
            {
                AddRowToTableWithAllCellsHavingValue(i);
            }

            // Add one last blank row to table for the add row button
            AddRowToTableWithAllCellsHavingValue(int.MaxValue);
            tvColorSchemes.Update();
        }

        private void AddRowToTableWithAllCellsHavingValue(int i)
        {            
            var tbl = tvColorSchemes.Table;

            var r = tbl.Rows.Add();
            for(int j = 0;j<tbl.Columns.Count;j++)
            {
                r[j] = i;
            }
        }
    }
}
