//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Terminal.Gui;
using Attribute = Terminal.Gui.Attribute;

namespace TerminalGuiDesigner.UI.Windows;

/// <summary>
/// Prompts user to pick a two <see cref="Color"/> to make an <see cref="Attribute"/>.
/// </summary>
public partial class ColorPicker
{
    /// <summary>
    /// The combination of foreground and background <see cref="Color"/> the user chose.
    /// </summary>
    public Terminal.Gui.Attribute? Result { get; internal set; }

    /// <summary>
    /// True if user closed dialog with cancel.
    /// </summary>
    public bool Cancelled { get; internal set; }

    /// <summary>
    /// Creates a new instance of the <see cref="ColorPicker"/> class.
    /// </summary>
    /// <param name="currentValue"></param>
    public ColorPicker(Attribute? currentValue)
    {
        InitializeComponent();

        if (currentValue != null)
        {
            radiogroup1.SelectedItem = (int)currentValue.Value.Foreground;
            radiogroup2.SelectedItem = (int)currentValue.Value.Background;
        }

        lblPreview.ColorScheme = new ColorScheme();
        UpdatePreview();

        radiogroup1.SelectedItemChanged += (s,e) => UpdatePreview();
        radiogroup2.SelectedItemChanged += (s,e) => UpdatePreview();

        btnOk.Clicked += (s, e) => Ok();
        btnCancel.Clicked += (s, e) => Cancel();
    }

    private void Ok()
    {
        Cancelled = false;
        Result = GetColor();
        Application.RequestStop();
    }
    private void Cancel()
    {
        Cancelled = true;
        Result = null;
        Application.RequestStop();
    }

    private void UpdatePreview()
    {
        lblPreview.ColorScheme.Normal = GetColor();
        lblPreview.SetNeedsDisplay();
    }

    private Attribute GetColor()
    {
        return new Attribute((Color)radiogroup1.SelectedItem, (Color)radiogroup2.SelectedItem);
    }
}