
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.15.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace TerminalGuiDesigner.UI.Windows {
    using System;
    using Terminal.Gui;
    
    
    public partial class ColorSchemeEditor : Terminal.Gui.Dialog {
        
        private Terminal.Gui.Label label2;
        
        private Terminal.Gui.Label lblForegroundNormal;
        
        private Terminal.Gui.Label label1;
        
        private Terminal.Gui.Label lblBackgroundNormal;
        
        private Terminal.Gui.Button btnEditNormal;
        
        private Terminal.Gui.Label label22;
        
        private Terminal.Gui.Label lblForegroundHotNormal;
        
        private Terminal.Gui.Label lblHotNormalSlash;
        
        private Terminal.Gui.Label lblBackgroundHotNormal;
        
        private Terminal.Gui.Button btnEditHotNormal;
        
        private Terminal.Gui.Label lblFocus;
        
        private Terminal.Gui.Label lblForegroundFocus;
        
        private Terminal.Gui.Label lblHotNormalSlash2;
        
        private Terminal.Gui.Label lblBackgroundFocus;
        
        private Terminal.Gui.Button btnEditFocus;
        
        private Terminal.Gui.Label label223;
        
        private Terminal.Gui.Label lblForegroundHotFocus;
        
        private Terminal.Gui.Label lblHotNormalSlash3;
        
        private Terminal.Gui.Label lblBackgroundHotFocus;
        
        private Terminal.Gui.Button btnEditHotFocus;
        
        private Terminal.Gui.Label label2232;
        
        private Terminal.Gui.Label lblForegroundDisabled;
        
        private Terminal.Gui.Label lblHotNormalSlash32;
        
        private Terminal.Gui.Label lblBackgroundDisabled;
        
        private Terminal.Gui.Button btnEditDisabled;
        
        private Terminal.Gui.Button btnOk;
        
        private Terminal.Gui.Button btnCancel;
        
        private void InitializeComponent() {
            this.Width = 31;
            this.Height = 9;
            this.X = Pos.Center();
            this.Y = Pos.Center();
            this.Modal = true;
            this.Text = "";
            this.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.Border.BorderBrush = Terminal.Gui.Color.Blue;
            this.Border.Effect3D = true;
            this.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Title = "Color Scheme Editor";
            this.label2 = new Terminal.Gui.Label();
            this.label2.Width = 10;
            this.label2.Height = 1;
            this.label2.X = 1;
            this.label2.Y = 0;
            this.label2.Data = "label2";
            this.label2.Text = "Normal   :";
            this.label2.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label2);
            this.lblForegroundNormal = new Terminal.Gui.Label();
            this.lblForegroundNormal.Width = 1;
            this.lblForegroundNormal.Height = 1;
            this.lblForegroundNormal.X = Pos.Right(label2) + 1;
            this.lblForegroundNormal.Y = 0;
            this.lblForegroundNormal.Data = "lblForegroundNormal";
            this.lblForegroundNormal.Text = "";
            this.lblForegroundNormal.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.lblForegroundNormal);
            this.label1 = new Terminal.Gui.Label();
            this.label1.Width = 1;
            this.label1.Height = 1;
            this.label1.X = 13;
            this.label1.Y = 0;
            this.label1.Data = "label1";
            this.label1.Text = "\\";
            this.label1.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label1);
            this.lblBackgroundNormal = new Terminal.Gui.Label();
            this.lblBackgroundNormal.Width = 1;
            this.lblBackgroundNormal.Height = 1;
            this.lblBackgroundNormal.X = Pos.Right(label2) + 3;
            this.lblBackgroundNormal.Y = 0;
            this.lblBackgroundNormal.Data = "lblBackgroundNormal";
            this.lblBackgroundNormal.Text = "";
            this.lblBackgroundNormal.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.lblBackgroundNormal);
            this.btnEditNormal = new Terminal.Gui.Button();
            this.btnEditNormal.Width = 13;
            this.btnEditNormal.X = 15;
            this.btnEditNormal.Y = 0;
            this.btnEditNormal.Data = "btnEditNormal";
            this.btnEditNormal.Text = "Choose...";
            this.btnEditNormal.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.btnEditNormal.IsDefault = false;
            this.Add(this.btnEditNormal);
            this.label22 = new Terminal.Gui.Label();
            this.label22.Width = 10;
            this.label22.Height = 1;
            this.label22.X = 1;
            this.label22.Y = 1;
            this.label22.Data = "label22";
            this.label22.Text = "HotNormal:";
            this.label22.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label22);
            this.lblForegroundHotNormal = new Terminal.Gui.Label();
            this.lblForegroundHotNormal.Width = 1;
            this.lblForegroundHotNormal.Height = 1;
            this.lblForegroundHotNormal.X = Pos.Right(label22) + 1;
            this.lblForegroundHotNormal.Y = 1;
            this.lblForegroundHotNormal.Data = "lblForegroundHotNormal";
            this.lblForegroundHotNormal.Text = "";
            this.lblForegroundHotNormal.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.lblForegroundHotNormal);
            this.lblHotNormalSlash = new Terminal.Gui.Label();
            this.lblHotNormalSlash.Width = 1;
            this.lblHotNormalSlash.Height = 1;
            this.lblHotNormalSlash.X = 13;
            this.lblHotNormalSlash.Y = 1;
            this.lblHotNormalSlash.Data = "lblHotNormalSlash";
            this.lblHotNormalSlash.Text = "\\";
            this.lblHotNormalSlash.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.lblHotNormalSlash);
            this.lblBackgroundHotNormal = new Terminal.Gui.Label();
            this.lblBackgroundHotNormal.Width = 1;
            this.lblBackgroundHotNormal.Height = 1;
            this.lblBackgroundHotNormal.X = Pos.Right(label22) + 3;
            this.lblBackgroundHotNormal.Y = 1;
            this.lblBackgroundHotNormal.Data = "lblBackgroundHotNormal";
            this.lblBackgroundHotNormal.Text = "";
            this.lblBackgroundHotNormal.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.lblBackgroundHotNormal);
            this.btnEditHotNormal = new Terminal.Gui.Button();
            this.btnEditHotNormal.Width = 13;
            this.btnEditHotNormal.X = 15;
            this.btnEditHotNormal.Y = 1;
            this.btnEditHotNormal.Data = "btnEditHotNormal";
            this.btnEditHotNormal.Text = "Choose...";
            this.btnEditHotNormal.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.btnEditHotNormal.IsDefault = false;
            this.Add(this.btnEditHotNormal);
            this.lblFocus = new Terminal.Gui.Label();
            this.lblFocus.Width = 10;
            this.lblFocus.Height = 1;
            this.lblFocus.X = 1;
            this.lblFocus.Y = 2;
            this.lblFocus.Data = "lblFocus";
            this.lblFocus.Text = "Focus    :";
            this.lblFocus.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.lblFocus);
            this.lblForegroundFocus = new Terminal.Gui.Label();
            this.lblForegroundFocus.Width = 1;
            this.lblForegroundFocus.Height = 1;
            this.lblForegroundFocus.X = Pos.Right(lblFocus) + 1;
            this.lblForegroundFocus.Y = 2;
            this.lblForegroundFocus.Data = "lblForegroundFocus";
            this.lblForegroundFocus.Text = "";
            this.lblForegroundFocus.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.lblForegroundFocus);
            this.lblHotNormalSlash2 = new Terminal.Gui.Label();
            this.lblHotNormalSlash2.Width = 1;
            this.lblHotNormalSlash2.Height = 1;
            this.lblHotNormalSlash2.X = 13;
            this.lblHotNormalSlash2.Y = 2;
            this.lblHotNormalSlash2.Data = "lblHotNormalSlash2";
            this.lblHotNormalSlash2.Text = "\\";
            this.lblHotNormalSlash2.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.lblHotNormalSlash2);
            this.lblBackgroundFocus = new Terminal.Gui.Label();
            this.lblBackgroundFocus.Width = 1;
            this.lblBackgroundFocus.Height = 1;
            this.lblBackgroundFocus.X = Pos.Right(lblFocus) + 3;
            this.lblBackgroundFocus.Y = 2;
            this.lblBackgroundFocus.Data = "lblBackgroundFocus";
            this.lblBackgroundFocus.Text = "";
            this.lblBackgroundFocus.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.lblBackgroundFocus);
            this.btnEditFocus = new Terminal.Gui.Button();
            this.btnEditFocus.Width = 13;
            this.btnEditFocus.X = 15;
            this.btnEditFocus.Y = 2;
            this.btnEditFocus.Data = "btnEditFocus";
            this.btnEditFocus.Text = "Choose...";
            this.btnEditFocus.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.btnEditFocus.IsDefault = false;
            this.Add(this.btnEditFocus);
            this.label223 = new Terminal.Gui.Label();
            this.label223.Width = 10;
            this.label223.Height = 1;
            this.label223.X = 1;
            this.label223.Y = 3;
            this.label223.Data = "label223";
            this.label223.Text = "HotFocus :";
            this.label223.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label223);
            this.lblForegroundHotFocus = new Terminal.Gui.Label();
            this.lblForegroundHotFocus.Width = 1;
            this.lblForegroundHotFocus.Height = 1;
            this.lblForegroundHotFocus.X = Pos.Right(label223) + 1;
            this.lblForegroundHotFocus.Y = 3;
            this.lblForegroundHotFocus.Data = "lblForegroundHotFocus";
            this.lblForegroundHotFocus.Text = "";
            this.lblForegroundHotFocus.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.lblForegroundHotFocus);
            this.lblHotNormalSlash3 = new Terminal.Gui.Label();
            this.lblHotNormalSlash3.Width = 1;
            this.lblHotNormalSlash3.Height = 1;
            this.lblHotNormalSlash3.X = 13;
            this.lblHotNormalSlash3.Y = 3;
            this.lblHotNormalSlash3.Data = "lblHotNormalSlash3";
            this.lblHotNormalSlash3.Text = "\\";
            this.lblHotNormalSlash3.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.lblHotNormalSlash3);
            this.lblBackgroundHotFocus = new Terminal.Gui.Label();
            this.lblBackgroundHotFocus.Width = 1;
            this.lblBackgroundHotFocus.Height = 1;
            this.lblBackgroundHotFocus.X = Pos.Right(label223) + 3;
            this.lblBackgroundHotFocus.Y = 3;
            this.lblBackgroundHotFocus.Data = "lblBackgroundHotFocus";
            this.lblBackgroundHotFocus.Text = "";
            this.lblBackgroundHotFocus.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.lblBackgroundHotFocus);
            this.btnEditHotFocus = new Terminal.Gui.Button();
            this.btnEditHotFocus.Width = 13;
            this.btnEditHotFocus.X = 15;
            this.btnEditHotFocus.Y = 3;
            this.btnEditHotFocus.Data = "btnEditHotFocus";
            this.btnEditHotFocus.Text = "Choose...";
            this.btnEditHotFocus.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.btnEditHotFocus.IsDefault = false;
            this.Add(this.btnEditHotFocus);
            this.label2232 = new Terminal.Gui.Label();
            this.label2232.Width = 10;
            this.label2232.Height = 1;
            this.label2232.X = 1;
            this.label2232.Y = 4;
            this.label2232.Data = "label2232";
            this.label2232.Text = "Disabled :";
            this.label2232.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label2232);
            this.lblForegroundDisabled = new Terminal.Gui.Label();
            this.lblForegroundDisabled.Width = 1;
            this.lblForegroundDisabled.Height = 1;
            this.lblForegroundDisabled.X = Pos.Right(label2232) + 1;
            this.lblForegroundDisabled.Y = 4;
            this.lblForegroundDisabled.Data = "lblForegroundDisabled";
            this.lblForegroundDisabled.Text = "";
            this.lblForegroundDisabled.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.lblForegroundDisabled);
            this.lblHotNormalSlash32 = new Terminal.Gui.Label();
            this.lblHotNormalSlash32.Width = 1;
            this.lblHotNormalSlash32.Height = 1;
            this.lblHotNormalSlash32.X = 13;
            this.lblHotNormalSlash32.Y = 4;
            this.lblHotNormalSlash32.Data = "lblHotNormalSlash32";
            this.lblHotNormalSlash32.Text = "\\";
            this.lblHotNormalSlash32.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.lblHotNormalSlash32);
            this.lblBackgroundDisabled = new Terminal.Gui.Label();
            this.lblBackgroundDisabled.Width = 1;
            this.lblBackgroundDisabled.Height = 1;
            this.lblBackgroundDisabled.X = Pos.Right(label2232) + 3;
            this.lblBackgroundDisabled.Y = 4;
            this.lblBackgroundDisabled.Data = "lblBackgroundDisabled";
            this.lblBackgroundDisabled.Text = "";
            this.lblBackgroundDisabled.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.lblBackgroundDisabled);
            this.btnEditDisabled = new Terminal.Gui.Button();
            this.btnEditDisabled.Width = 13;
            this.btnEditDisabled.X = 15;
            this.btnEditDisabled.Y = 4;
            this.btnEditDisabled.Data = "btnEditDisabled";
            this.btnEditDisabled.Text = "Choose...";
            this.btnEditDisabled.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.btnEditDisabled.IsDefault = false;
            this.Add(this.btnEditDisabled);
            this.btnOk = new Terminal.Gui.Button();
            this.btnOk.Width = 6;
            this.btnOk.X = 3;
            this.btnOk.Y = 6;
            this.btnOk.Data = "btnOk";
            this.btnOk.Text = "Ok";
            this.btnOk.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.btnOk.IsDefault = false;
            this.Add(this.btnOk);
            this.btnCancel = new Terminal.Gui.Button();
            this.btnCancel.Width = 10;
            this.btnCancel.X = 13;
            this.btnCancel.Y = 6;
            this.btnCancel.Data = "btnCancel";
            this.btnCancel.Text = "Cancel";
            this.btnCancel.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.btnCancel.IsDefault = false;
            this.Add(this.btnCancel);
        }
    }
}
