
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v2.0.0.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace TerminalGuiDesigner.UI.Windows {
    using System;
    using Terminal.Gui;
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Drawing;
    
    
    public partial class KeyBindingsUI : Terminal.Gui.Dialog {
        
        private Terminal.Gui.ColorScheme dialogBackground;
        
        private Terminal.Gui.ColorScheme buttons;
        
        private Terminal.Gui.TableView tableView;
        
        private Terminal.Gui.View buttonPanel;
        
        private Terminal.Gui.Button btnSave;
        
        private Terminal.Gui.Button btnCancel;
        
        private void InitializeComponent() {
            this.btnCancel = new Terminal.Gui.Button();
            this.btnSave = new Terminal.Gui.Button();
            this.buttonPanel = new Terminal.Gui.View();
            this.tableView = new Terminal.Gui.TableView();
            this.dialogBackground = new Terminal.Gui.ColorScheme(new Terminal.Gui.Attribute(4294967295u, 4285953654u), new Terminal.Gui.Attribute(4294967295u, 4285953654u), new Terminal.Gui.Attribute(4294967295u, 4285953654u), new Terminal.Gui.Attribute(4278190080u, 4278190080u), new Terminal.Gui.Attribute(4294967295u, 4285953654u));
            this.buttons = new Terminal.Gui.ColorScheme(new Terminal.Gui.Attribute(4285953654u, 4294967295u), new Terminal.Gui.Attribute(4294901760u, 4294967040u), new Terminal.Gui.Attribute(4278190080u, 4294967295u), new Terminal.Gui.Attribute(4278190080u, 4278190080u), new Terminal.Gui.Attribute(4278190080u, 4294967040u));
            this.Width = Dim.Percent(90);
            this.Height = Dim.Percent(80);
            this.X = Pos.Center();
            this.Y = Pos.Center();
            this.Visible = true;
            this.Arrangement = (Terminal.Gui.ViewArrangement.Movable | Terminal.Gui.ViewArrangement.Overlapped);
            this.ColorScheme = this.dialogBackground;
            this.CanFocus = true;
            this.ShadowStyle = Terminal.Gui.ShadowStyle.Transparent;
            this.Modal = true;
            this.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Title = "Keybindings";
            this.tableView.Width = Dim.Fill(0);
            this.tableView.Height = Dim.Fill(3);
            this.tableView.X = 0;
            this.tableView.Y = 0;
            this.tableView.Visible = true;
            this.tableView.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.tableView.CanFocus = true;
            this.tableView.ShadowStyle = Terminal.Gui.ShadowStyle.None;
            this.tableView.Data = "tableView";
            this.tableView.TextAlignment = Terminal.Gui.Alignment.Start;
            this.tableView.FullRowSelect = false;
            this.tableView.Style.AlwaysShowHeaders = false;
            this.tableView.Style.ExpandLastColumn = true;
            this.tableView.Style.InvertSelectedCellFirstCharacter = false;
            this.tableView.Style.ShowHorizontalHeaderOverline = true;
            this.tableView.Style.ShowHorizontalHeaderUnderline = true;
            this.tableView.Style.ShowVerticalCellLines = true;
            this.tableView.Style.ShowVerticalHeaderLines = true;
            System.Data.DataTable tableViewTable;
            tableViewTable = new System.Data.DataTable();
            System.Data.DataColumn tableViewTableColumn0;
            tableViewTableColumn0 = new System.Data.DataColumn();
            tableViewTableColumn0.ColumnName = "Column 0";
            tableViewTable.Columns.Add(tableViewTableColumn0);
            System.Data.DataColumn tableViewTableColumn1;
            tableViewTableColumn1 = new System.Data.DataColumn();
            tableViewTableColumn1.ColumnName = "Column 1";
            tableViewTable.Columns.Add(tableViewTableColumn1);
            System.Data.DataColumn tableViewTableColumn2;
            tableViewTableColumn2 = new System.Data.DataColumn();
            tableViewTableColumn2.ColumnName = "Column 2";
            tableViewTable.Columns.Add(tableViewTableColumn2);
            System.Data.DataColumn tableViewTableColumn3;
            tableViewTableColumn3 = new System.Data.DataColumn();
            tableViewTableColumn3.ColumnName = "Column 3";
            tableViewTable.Columns.Add(tableViewTableColumn3);
            this.tableView.Table = new Terminal.Gui.DataTableSource(tableViewTable);
            this.Add(this.tableView);
            this.buttonPanel.Width = 32;
            this.buttonPanel.Height = 3;
            this.buttonPanel.X = Pos.Center();
            this.buttonPanel.Y = Pos.AnchorEnd(3);
            this.buttonPanel.Visible = true;
            this.buttonPanel.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.buttonPanel.CanFocus = true;
            this.buttonPanel.ShadowStyle = Terminal.Gui.ShadowStyle.None;
            this.buttonPanel.Data = "buttonPanel";
            this.buttonPanel.Text = "";
            this.buttonPanel.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.buttonPanel);
            this.btnSave.Width = Dim.Auto();
            this.btnSave.Height = Dim.Auto();
            this.btnSave.X = 1;
            this.btnSave.Y = 1;
            this.btnSave.Visible = true;
            this.btnSave.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.btnSave.ColorScheme = this.buttons;
            this.btnSave.CanFocus = true;
            this.btnSave.ShadowStyle = Terminal.Gui.ShadowStyle.Opaque;
            this.btnSave.Data = "btnSave";
            this.btnSave.Text = "Save";
            this.btnSave.TextAlignment = Terminal.Gui.Alignment.Center;
            this.btnSave.IsDefault = false;
            this.buttonPanel.Add(this.btnSave);
            this.btnCancel.Width = Dim.Auto();
            this.btnCancel.Height = Dim.Auto();
            this.btnCancel.X = 19;
            this.btnCancel.Y = 1;
            this.btnCancel.Visible = true;
            this.btnCancel.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.btnCancel.ColorScheme = this.buttons;
            this.btnCancel.CanFocus = true;
            this.btnCancel.ShadowStyle = Terminal.Gui.ShadowStyle.Opaque;
            this.btnCancel.Data = "btnCancel";
            this.btnCancel.Text = "Cancel";
            this.btnCancel.TextAlignment = Terminal.Gui.Alignment.Center;
            this.btnCancel.IsDefault = false;
            this.buttonPanel.Add(this.btnCancel);
        }
    }
}
