
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v2.0.0.0
//      You can make changes to this file and they will not be overwritten when saving.
//  </auto-generated>
// -----------------------------------------------------------------------------

using System.Reflection;
using System.Text.Json;
using Terminal.Gui.App;
using Terminal.Gui.Drawing;
using Terminal.Gui.Views;
using Attribute = System.Attribute;

namespace TerminalGuiDesigner.UI.Windows {
    using Terminal.Gui;
    using Terminal.Gui.Input;

    public partial class KeyBindingsUI {
        private readonly IApplication app;
        private readonly KeyMap keyMap;
        private readonly PropertyInfo[] _props;

        public bool Save { get; set; } = false;

        public KeyBindingsUI(IApplication app, KeyMap keyMap) {
            this.app = app;
            this.keyMap = keyMap;
            InitializeComponent();

            _props = typeof(KeyMap).GetProperties()
                .Where(p=>p.PropertyType == typeof(string))
                .OrderBy(p=>p.Name)
                .ToArray();
            
            tableView.Table = new EnumerableTableSource<PropertyInfo>(_props,
                new Dictionary<string, Func<PropertyInfo, object>>()
                {
                    { "Function", p => p.Name },
                    { "Key", p => p.GetValue(this.keyMap) }
                });

            var keyStyle = tableView.Style.GetOrCreateColumnStyle(1);

            var badCellColor = CloneSchemeButMake(tableView.GetScheme(),Color.Red);

            keyStyle.ColorGetter = (k) =>
            {
                var val = _props[k.RowIndex].GetValue(this.keyMap);
                var matches = _props.Select(k => k.GetValue(this.keyMap)).Count(v => Equals(v,val));
                if (matches > 1)
                {
                    return badCellColor;
                }

                // Use normal color scheme
                return null;
            };

            tableView.KeyBindings.Clear(Command.Accept);
            tableView.KeyBindings.Add(Key.Enter, new KeyBinding([Command.Activate]));
            tableView.Activating += (s, e) =>
            {                
                var prop = _props[tableView.Value.Cursor.Y];
                var k = Modals.GetShortcut(app);
                prop.SetValue(this.keyMap,k.ToString());
                this.SetNeedsDraw();
                e.Handled = true;
            };
            btnReset.Accepting += (s, e) =>
            {
                var defaultMap = new KeyMap();
                foreach (var p in _props)
                {
                    var def = p.GetValue(defaultMap);
                    p.SetValue(this.keyMap, def);
                    this.SetNeedsDraw();
                }
            };

            btnSave.Accepting += (s, e) =>
            {
                Save = true;
                e.Handled = true;
                app.RequestStop();
            };
            btnCancel.Accepting += (s, e) =>
            {
                e.Handled = true;
                app.RequestStop();
            };
        }

        private Scheme CloneSchemeButMake(Scheme cs,Color color)
        {
            return new Scheme
            {
                Disabled = cs.Disabled,
                Focus = cs.Focus,
                HotFocus = cs.HotFocus,
                HotNormal = cs.HotNormal,
                Normal = new Terminal.Gui.Drawing.Attribute(color, cs.Normal.Background)
            };
        }
    }
}
