
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v2.0.0.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace TerminalGuiDesigner.UI.Windows {
    using System;
    using Terminal.Gui;
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Drawing;
    
    
    public partial class KeyBindingsUI : Terminal.Gui.Dialog {
        
        private Terminal.Gui.View buttonPanel;
        
        private Terminal.Gui.Button btnSave;
        
        private Terminal.Gui.Button btnCancel;
        
        private void InitializeComponent() {
            this.btnCancel = new Terminal.Gui.Button();
            this.btnSave = new Terminal.Gui.Button();
            this.buttonPanel = new Terminal.Gui.View();
            this.Width = Dim.Percent(90);
            this.Height = Dim.Percent(80);
            this.X = Pos.Center();
            this.Y = Pos.Center();
            this.Visible = true;
            this.Arrangement = (Terminal.Gui.ViewArrangement.Movable | Terminal.Gui.ViewArrangement.Overlapped);
            this.CanFocus = true;
            this.ShadowStyle = Terminal.Gui.ShadowStyle.Transparent;
            this.Modal = true;
            this.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Title = "Keybindings";
            this.buttonPanel.Width = 34;
            this.buttonPanel.Height = 6;
            this.buttonPanel.X = 38;
            this.buttonPanel.Y = 11;
            this.buttonPanel.Visible = true;
            this.buttonPanel.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.buttonPanel.CanFocus = false;
            this.buttonPanel.ShadowStyle = Terminal.Gui.ShadowStyle.None;
            this.buttonPanel.Data = "buttonPanel";
            this.buttonPanel.Text = "";
            this.buttonPanel.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.buttonPanel);
            this.btnSave.Width = Dim.Auto();
            this.btnSave.Height = Dim.Auto();
            this.btnSave.X = 1;
            this.btnSave.Y = 3;
            this.btnSave.Visible = true;
            this.btnSave.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.btnSave.CanFocus = true;
            this.btnSave.ShadowStyle = Terminal.Gui.ShadowStyle.Opaque;
            this.btnSave.Data = "btnSave";
            this.btnSave.Text = "Save";
            this.btnSave.TextAlignment = Terminal.Gui.Alignment.Center;
            this.btnSave.IsDefault = false;
            this.buttonPanel.Add(this.btnSave);
            this.btnCancel.Width = Dim.Auto();
            this.btnCancel.Height = Dim.Auto();
            this.btnCancel.X = 19;
            this.btnCancel.Y = 3;
            this.btnCancel.Visible = true;
            this.btnCancel.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.btnCancel.CanFocus = true;
            this.btnCancel.ShadowStyle = Terminal.Gui.ShadowStyle.Opaque;
            this.btnCancel.Data = "btnCancel";
            this.btnCancel.Text = "Cancel";
            this.btnCancel.TextAlignment = Terminal.Gui.Alignment.Center;
            this.btnCancel.IsDefault = false;
            this.buttonPanel.Add(this.btnCancel);
        }
    }
}
