//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TerminalGuiDesigner {
    using Terminal.Gui;
    
    
    public partial class LoadingDialog {
        
        public LoadingDialog(FileInfo file) {
            InitializeComponent();

            lblLoadingFile.Text = $"Loading {file.Name}";
        }
    }
}
