//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YourNamespace {
    using Terminal.Gui;
    
    
    public partial class PointDesigner {
        
        public PointDesigner() {
            InitializeComponent();
        }
    }
}
