//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TerminalGuiDesigner {
    using Terminal.Gui;
    
    
    public partial class PointEditor {
        
        public PointEditor() {
            InitializeComponent();
        }
    }
}
