//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using JetBrains.Annotations;
using Terminal.Gui.App;
using Terminal.Gui.Drawing;
using Terminal.Gui.Input;
using Terminal.Gui.ViewBase;
using Terminal.Gui.Views;

namespace TerminalGuiDesigner.UI.Windows;

using Terminal.Gui;
using System.Linq;
using TerminalGuiDesigner;
using TerminalGuiDesigner.ToCode;
using TerminalGuiDesigner.UI.Windows;

/// <summary>
/// Editor for the <see cref="Pos"/> type.
/// </summary>
public partial class PosEditor : Dialog, IValueGetterDialog {

    private readonly IApplication app;
    private Design design;
    private readonly Dictionary<string, Design> _siblings;

    /// <summary>
    /// Users configured <see cref="Pos"/> (assembled from radio button
    /// selected and text values entered - offset etc).
    /// </summary>
    [CanBeNull]
    public object ActualResult { get; private set; }

    /// <summary>
    /// True if user cancelled the dialog instead of hitting Ok.
    /// </summary>
    public bool Cancelled { get; private set; }

    /// <summary>
    /// Prompt user to create a new <see cref="Pos"/> value to populate
    /// on <paramref name="design"/> with.
    /// </summary>
    /// <param name="app">The application instance.</param>
    /// <param name="design">What to set the value on.</param>
    /// <param name="oldValue">The current value for the property.</param>
    public PosEditor(IApplication app, Design design, Pos oldValue) {
        InitializeComponent();

        this.app = app;
        this.design = design;

        Title = "Pos Designer";
        Border.LineStyle = LineStyle.Double;

        rgPosType.KeyDown += RgPosType_KeyPress;

        btnOk.Accepting += BtnOk_Clicked;
        btnCancel.Accepting += BtnCancel_Clicked;
        Cancelled = true;

        _siblings = design.GetSiblings().ToDictionary(
            d=>d.FieldName,
            d=>d);

        tbRelativeTo.Autocomplete.SuggestionGenerator = new SingleWordSuggestionGenerator()
        {
            AllSuggestions = _siblings.Keys.OrderBy(a => a).ToList()
        };

        var val = oldValue;
        if(val.GetPosType(_siblings.Values.ToList(),
               out var type,out var value,out var relativeTo,out var side, out var offset))
        {
            switch(type)
            {
                case PosType.Absolute:
                    rgPosType.Value = 0;
                    break;
                case PosType.Percent:
                    rgPosType.Value = 1;
                    break;
                case PosType.Relative:
                    rgPosType.Value = 2;
                    if(relativeTo != null)
                        tbRelativeTo.Text = relativeTo.FieldName;
                    rgSide.Value = (int)side;
                    break;
                case PosType.Center:
                    rgPosType.Value = 3;                        
                    break;
                case PosType.AnchorEnd:
                    rgPosType.Value = 4;
                    break;
            }

            tbValue.Text = value.ToString("G5");
            tbOffset.Text = offset.ToString();
        }

        SetupForCurrentPosType();

        rgPosType.ValueChanged += DdType_SelectedItemChanged;

    }

    private void RgPosType_KeyPress(object sender, Key key)
    {
        var c = (char)key;
        
        // if user types in some text change the focus to the text box to enable entering digits
        if ((key == Key.Backspace || char.IsDigit(c)) && tbValue.Visible)
        {
            tbValue?.FocusDeepest(NavigationDirection.Forward,TabBehavior.TabStop);
        }            
    }

    private void DdType_SelectedItemChanged(object sender, ValueChangedEventArgs<int?> e)
    {
        SetupForCurrentPosType();            
    }

    private void SetupForCurrentPosType()
    {
        
        switch(GetPosType())
        {
            case PosType.Percent:
                lblRelativeTo.Visible = false;
                tbRelativeTo.Visible = false;
                lblSide.Visible = false;
                rgSide.Visible = false;
                
                lblValue.Y = 1;
                lblValue.Visible = true;
                tbValue.Visible = true;
                
                lblOffset.Y = 3;
                lblOffset.Visible = true;
                
                tbOffset.Y = 3;
                tbOffset.Visible = true;

                SetNeedsDraw();
                break;
            case PosType.Center:
                lblRelativeTo.Visible = false;
                tbRelativeTo.Visible = false;
                lblSide.Visible = false;
                rgSide.Visible = false;
                
                lblValue.Visible = false;
                tbValue.Visible = false;
                
                lblOffset.Y = 1;
                lblOffset.Visible = true;
                tbOffset.Y = 1;
                tbOffset.Visible = true;

                SetNeedsDraw();
                break;
            case PosType.Absolute:
            case PosType.AnchorEnd:
                tbRelativeTo.Visible = false;
                lblRelativeTo.Visible = false;
                lblSide.Visible = false;
                rgSide.Visible = false;

                lblValue.Y = 1;
                lblValue.Visible = true;
                tbValue.Visible = true;

                lblOffset.Visible = false;
                tbOffset.Visible = false;
                SetNeedsDraw();
                break;
            case PosType.Relative:
                lblRelativeTo.Y = 1;
                lblRelativeTo.Visible = true;
                tbRelativeTo.Y = 1;
                tbRelativeTo.Visible = true;

                lblSide.Y = 3;
                lblSide.Visible = true;

                rgSide.IsInitialized = false;
                rgSide.Y = 3;
                rgSide.Visible = true;
                rgSide.IsInitialized = true;

                lblValue.Visible = false;
                tbValue.Visible = false;

                lblOffset.Y = 7;
                lblOffset.Visible = true;
                tbOffset.Y = 7;
                tbOffset.Visible = true;
                SetNeedsDraw();
                break;

            default: throw new ArgumentOutOfRangeException();
        }
    }

    private void BtnCancel_Clicked(object sender, CommandEventArgs e)
    {
        e.Handled = true;
        Cancelled = true;
        app.RequestStop();
    }

    private void BtnOk_Clicked(object sender, CommandEventArgs e)
    {
        e.Handled = true;
        if(GetPosType() == PosType.AnchorEnd && GetValue(out var value) && value <=0)
        {
            if (!ChoicesDialog.Confirm(app, "Anchor Without Margin", "Using AnchorEnd without a margin will result in a point outside of parent bounds.\nAre you sure?"))
            {
                return;
            }
        }

        Cancelled = !BuildPos(out var result);
        ActualResult = result;
        app.RequestStop();
    }

    private bool BuildPos(out Pos result)
    {
        // pick what type of Pos they want
        var type = GetPosType();

        switch (type)
        {
            case PosType.Absolute:
                return BuildPosAbsolute(out result);
            case PosType.Relative:
                return BuildPosRelative(out result);
            case PosType.Percent:
                return BuildPosPercent(out result);
            case PosType.Center:
                return BuildPosCenter(out result);
            case PosType.AnchorEnd:
                return BuildPosAnchorEnd(out result);

            default: throw new ArgumentOutOfRangeException();

        }
    }

    private PosType GetPosType()
    {
        return Enum.Parse<PosType>(rgPosType.Labels[rgPosType.Value ?? 0].ToString());
    }


    private Side? GetSide()
    {
        return rgSide.Value == null ? null : (Side)rgSide.Value;
    }

    private bool GetOffset(out int offset)
    {
        // blank text box counts as 0
        if(string.IsNullOrWhiteSpace(tbOffset.Text.ToString()))
        {
            offset = 0;
            return true;
        }

        if (int.TryParse(tbOffset.Text.ToString(), out offset))
        {
            return true;
        }
        else
        {
            offset = 0;
            return false;
        }
    }

    private bool BuildPosRelative(out Pos result)
    {
        var key = tbRelativeTo.Text;

        var relativeTo = (!string.IsNullOrWhiteSpace(key)) && _siblings.TryGetValue(key, out var d) ? d : null;

        if (relativeTo != null)
        {
            var side = GetSide();

            if (side != null)
            {
                GetOffset(out int offset);

                result = PosExtensions.CreatePosRelative(relativeTo, side.Value,offset);
                return true;
            }
        }

        // Its got no side or no relative to control
        result = null;
        return false;
    }

    private bool BuildPosAbsolute(out Pos result)
    {
        if (GetValue(out int newPos))
        {
            result = Pos.Absolute(newPos);
            return true;
        }

        result = null;
        return false;
    }

    private bool BuildPosAnchorEnd(out Pos result)
    {
        if (GetValue(out int newPos))
        {
            result = Pos.AnchorEnd(newPos);
            return true;
        }

        result = null;
        return false;
    }

    private bool GetValue(out int newPos)
    {
        // blank text box counts as 0
        if(string.IsNullOrWhiteSpace(tbValue.Text.ToString()))
        {
            newPos = 0;
            return true;
        }

        return int.TryParse(tbValue.Text.ToString(),out newPos);
    }

    private bool BuildPosPercent(out Pos result)
    {
        if (GetValue(out int newPercent))
        {
            result = Pos.Percent(newPercent);

            if (GetOffset(out int offset) && offset != 0)
            {
                result = result + offset;
                return true;
            }

            return true;
        }

        result = null;
        return false;
    }
    private bool BuildPosCenter(out Pos result)
    {
        result = Pos.Center();

        if (GetOffset(out int offset) && offset != 0)
        {
            result = result + offset;
            return true;
        }

        return true;
    }
}
