//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TerminalGuiDesigner.UI.Windows {
    using System;
    using Terminal.Gui;
    
    
    public partial class PosEditor {
        
        private Terminal.Gui.RadioGroup rgPosType;
        
        private Terminal.Gui.Label lblValue;
        
        private Terminal.Gui.TextField tbValue;
        
        private Terminal.Gui.Label lblRelativeTo;
        
        private Terminal.Gui.ComboBox ddRelativeTo;
        
        private Terminal.Gui.Label lblSide;
        
        private Terminal.Gui.ComboBox ddSide;
        
        private Terminal.Gui.Label lblOffset;
        
        private Terminal.Gui.TextField tbOffset;
        
        private Terminal.Gui.Button btnOk;
        
        private Terminal.Gui.Button btnCancel;
        
        private void InitializeComponent() {
            this.rgPosType = new Terminal.Gui.RadioGroup();
            this.rgPosType.Data = "rgPosType";
            this.rgPosType.Text = "";
            this.rgPosType.Width = 11;
            this.rgPosType.Height = 3;
            this.rgPosType.X = 0;
            this.rgPosType.Y = 0;
            this.rgPosType.RadioLabels = new NStack.ustring[] {
                    "Absolute",
                    "Percent",
                    "Relative"};
            this.Add(this.rgPosType);
            this.lblValue = new Terminal.Gui.Label();
            this.lblValue.Data = "lblValue";
            this.lblValue.Text = "Value:";
            this.lblValue.Width = 6;
            this.lblValue.Height = 1;
            this.lblValue.X = 18;
            this.lblValue.Y = 0;
            this.Add(this.lblValue);
            this.tbValue = new Terminal.Gui.TextField();
            this.tbValue.Data = "tbValue";
            this.tbValue.Text = "";
            this.tbValue.Width = 15;
            this.tbValue.Height = 1;
            this.tbValue.X = Pos.Right(lblValue) + 1;
            this.tbValue.Y = Pos.Top(lblValue);
            this.Add(this.tbValue);
            this.lblRelativeTo = new Terminal.Gui.Label();
            this.lblRelativeTo.Data = "lblRelativeTo";
            this.lblRelativeTo.Text = "Relative To:";
            this.lblRelativeTo.Width = 12;
            this.lblRelativeTo.Height = 1;
            this.lblRelativeTo.X = 12;
            this.lblRelativeTo.Y = 2;
            this.Add(this.lblRelativeTo);
            this.ddRelativeTo = new Terminal.Gui.ComboBox();
            this.ddRelativeTo.Data = "ddRelativeTo";
            this.ddRelativeTo.Text = "";
            this.ddRelativeTo.Width = 15;
            this.ddRelativeTo.Height = 2;
            this.ddRelativeTo.X = Pos.Right(lblRelativeTo) + 1;
            this.ddRelativeTo.Y = Pos.Top(lblRelativeTo);
            this.Add(this.ddRelativeTo);
            this.lblSide = new Terminal.Gui.Label();
            this.lblSide.Data = "lblSide";
            this.lblSide.Text = "Side:";
            this.lblSide.Width = 5;
            this.lblSide.Height = 1;
            this.lblSide.X = 19;
            this.lblSide.Y = 4;
            this.Add(this.lblSide);
            this.ddSide = new Terminal.Gui.ComboBox();
            this.ddSide.Data = "ddSide";
            this.ddSide.Text = "";
            this.ddSide.Width = 15;
            this.ddSide.Height = 2;
            this.ddSide.X = Pos.Right(lblSide) + 1;
            this.ddSide.Y = Pos.Top(lblSide);
            this.Add(this.ddSide);
            this.lblOffset = new Terminal.Gui.Label();
            this.lblOffset.Data = "lblOffset";
            this.lblOffset.Text = "Offset:";
            this.lblOffset.Width = 7;
            this.lblOffset.Height = 1;
            this.lblOffset.X = 17;
            this.lblOffset.Y = 6;
            this.Add(this.lblOffset);
            this.tbOffset = new Terminal.Gui.TextField();
            this.tbOffset.Data = "tbOffset";
            this.tbOffset.Text = "";
            this.tbOffset.Width = 15;
            this.tbOffset.Height = 1;
            this.tbOffset.X = Pos.Right(lblOffset) + 1;
            this.tbOffset.Y = Pos.Top(lblOffset);
            this.Add(this.tbOffset);
            this.btnOk = new Terminal.Gui.Button();
            this.btnOk.Data = "btnOk";
            this.btnOk.Text = "Ok";
            this.btnOk.Width = 8;
            this.btnOk.Height = 1;
            this.btnOk.X = 11;
            this.btnOk.Y = 8;
            this.btnOk.IsDefault = true;
            this.Add(this.btnOk);
            this.btnCancel = new Terminal.Gui.Button();
            this.btnCancel.Data = "btnCancel";
            this.btnCancel.Text = "Cancel";
            this.btnCancel.Width = 10;
            this.btnCancel.Height = 1;
            this.btnCancel.X = 21;
            this.btnCancel.Y = 8;
            this.btnCancel.IsDefault = false;
            this.Add(this.btnCancel);
        }
    }
}
