//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YourNamespace {
    using System;
    using Terminal.Gui;
    
    
    public partial class PosEditor {
        
        private Terminal.Gui.Label lblType;
        
        private Terminal.Gui.ComboBox combobox1;
        
        private Terminal.Gui.Label lblValue;
        
        private Terminal.Gui.TextField tbValue;
        
        private Terminal.Gui.Label lblOffset;
        
        private Terminal.Gui.TextField tbOffset;
        
        private void InitializeComponent() {
            this.lblType = new Terminal.Gui.Label();
            this.lblType.Data = "lblType";
            this.lblType.Text = "Type:";
            this.lblType.Width = 6;
            this.lblType.Height = 1;
            this.lblType.X = 1;
            this.lblType.Y = 0;
            this.Add(this.lblType);
            this.combobox1 = new Terminal.Gui.ComboBox();
            this.combobox1.Data = "combobox1";
            this.combobox1.Text = "";
            this.combobox1.Width = 8;
            this.combobox1.Height = 2;
            this.combobox1.X = Pos.Right(lblType) + 1;
            this.combobox1.Y = Pos.Top(lblType);
            this.Add(this.combobox1);
            this.lblValue = new Terminal.Gui.Label();
            this.lblValue.Data = "lblValue";
            this.lblValue.Text = "Value:";
            this.lblValue.Width = 6;
            this.lblValue.Height = 1;
            this.lblValue.X = 3;
            this.lblValue.Y = 3;
            this.Add(this.lblValue);
            this.tbValue = new Terminal.Gui.TextField();
            this.tbValue.Data = "tbValue";
            this.tbValue.Text = "";
            this.tbValue.Width = 8;
            this.tbValue.Height = 1;
            this.tbValue.X = Pos.Right(lblValue) + 1;
            this.tbValue.Y = Pos.Top(lblValue);
            this.Add(this.tbValue);
            this.lblOffset = new Terminal.Gui.Label();
            this.lblOffset.Data = "lblOffset";
            this.lblOffset.Text = "Offset:";
            this.lblOffset.Width = 7;
            this.lblOffset.Height = 1;
            this.lblOffset.X = 3;
            this.lblOffset.Y = 5;
            this.Add(this.lblOffset);
            this.tbOffset = new Terminal.Gui.TextField();
            this.tbOffset.Data = "tbOffset";
            this.tbOffset.Text = "";
            this.tbOffset.Width = 4;
            this.tbOffset.Height = 1;
            this.tbOffset.X = Pos.Right(lblOffset) + 1;
            this.tbOffset.Y = Pos.Top(lblOffset);
            this.Add(this.tbOffset);
        }
    }
}
