
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v2.0.0.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace TerminalGuiDesigner.UI.Windows {
    using System;
    using Terminal.Gui;
    using Terminal.Gui.App;
    using Terminal.Gui.Drawing;
    using Terminal.Gui.Input;
    using Terminal.Gui.ViewBase;
    using Terminal.Gui.Views;
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Drawing;
    
    
    public partial class PosEditor : Terminal.Gui.Views.Dialog {
        
        private Terminal.Gui.Views.OptionSelector rgPosType;
        
        private Terminal.Gui.Views.Line Line1;
        
        private Terminal.Gui.Views.Label lblValue;
        
        private Terminal.Gui.Views.TextField tbValue;
        
        private Terminal.Gui.Views.Label lblRelativeTo;
        
        private Terminal.Gui.Views.TextField tbRelativeTo;
        
        private Terminal.Gui.Views.Label lblSide;
        
        private Terminal.Gui.Views.OptionSelector rgSide;
        
        private Terminal.Gui.Views.Label lblOffset;
        
        private Terminal.Gui.Views.TextField tbOffset;
        
        private Terminal.Gui.Views.Button btnOk;
        
        private Terminal.Gui.Views.Button btnCancel;
        
        private void InitializeComponent() {
            this.btnCancel = new Terminal.Gui.Views.Button();
            this.btnOk = new Terminal.Gui.Views.Button();
            this.tbOffset = new Terminal.Gui.Views.TextField();
            this.lblOffset = new Terminal.Gui.Views.Label();
            this.rgSide = new Terminal.Gui.Views.OptionSelector();
            this.lblSide = new Terminal.Gui.Views.Label();
            this.tbRelativeTo = new Terminal.Gui.Views.TextField();
            this.lblRelativeTo = new Terminal.Gui.Views.Label();
            this.tbValue = new Terminal.Gui.Views.TextField();
            this.lblValue = new Terminal.Gui.Views.Label();
            this.Line1 = new Terminal.Gui.Views.Line();
            this.rgPosType = new Terminal.Gui.Views.OptionSelector();
            this.Width = 47;
            this.Height = 16;
            this.X = Pos.Center();
            this.Y = Pos.Center();
            this.Visible = true;
            this.Arrangement = (Terminal.Gui.ViewBase.ViewArrangement.Movable | Terminal.Gui.ViewBase.ViewArrangement.Overlapped);
            this.CanFocus = true;
            this.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyle.Transparent;
            this.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Title = "";
            this.rgPosType.Width = 12;
            this.rgPosType.Height = 5;
            this.rgPosType.X = 1;
            this.rgPosType.Y = 1;
            this.rgPosType.Visible = true;
            this.rgPosType.Arrangement = Terminal.Gui.ViewBase.ViewArrangement.Fixed;
            this.rgPosType.CanFocus = true;
            this.rgPosType.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyle.None;
            this.rgPosType.Data = "rgPosType";
            this.rgPosType.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.rgPosType.Labels = new string[] {
                    "Absolute",
                    "Percent",
                    "Relative",
                    "Center",
                    "AnchorEnd"};
            this.Add(this.rgPosType);
            this.Line1.Width = 1;
            this.Line1.Height = 5;
            this.Line1.X = 14;
            this.Line1.Y = 1;
            this.Line1.Visible = true;
            this.Line1.Arrangement = Terminal.Gui.ViewBase.ViewArrangement.Fixed;
            this.Line1.CanFocus = false;
            this.Line1.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyle.None;
            this.Line1.Data = "Line1";
            this.Line1.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Line1.Orientation = Terminal.Gui.ViewBase.Orientation.Vertical;
            this.Add(this.Line1);
            this.lblValue.Width = 6;
            this.lblValue.Height = 1;
            this.lblValue.X = 22;
            this.lblValue.Y = 1;
            this.lblValue.Visible = true;
            this.lblValue.Arrangement = Terminal.Gui.ViewBase.ViewArrangement.Fixed;
            this.lblValue.CanFocus = false;
            this.lblValue.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyle.None;
            this.lblValue.Data = "lblValue";
            this.lblValue.Text = "Value:";
            this.lblValue.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Add(this.lblValue);
            this.tbValue.Width = 15;
            this.tbValue.Height = 1;
            this.tbValue.X = Pos.Right(lblValue) + 1;
            this.tbValue.Y = Pos.Top(lblValue);
            this.tbValue.Visible = true;
            this.tbValue.Arrangement = Terminal.Gui.ViewBase.ViewArrangement.Fixed;
            this.tbValue.CanFocus = true;
            this.tbValue.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyle.None;
            this.tbValue.Secret = false;
            this.tbValue.Data = "tbValue";
            this.tbValue.Text = "";
            this.tbValue.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Add(this.tbValue);
            this.lblRelativeTo.Width = 12;
            this.lblRelativeTo.Height = 1;
            this.lblRelativeTo.X = 16;
            this.lblRelativeTo.Y = 3;
            this.lblRelativeTo.Visible = true;
            this.lblRelativeTo.Arrangement = Terminal.Gui.ViewBase.ViewArrangement.Fixed;
            this.lblRelativeTo.CanFocus = false;
            this.lblRelativeTo.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyle.None;
            this.lblRelativeTo.Data = "lblRelativeTo";
            this.lblRelativeTo.Text = "Relative To:";
            this.lblRelativeTo.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Add(this.lblRelativeTo);
            this.tbRelativeTo.Width = 15;
            this.tbRelativeTo.Height = 1;
            this.tbRelativeTo.X = Pos.Right(lblOffset) + 1;
            this.tbRelativeTo.Y = 3;
            this.tbRelativeTo.Visible = true;
            this.tbRelativeTo.Arrangement = Terminal.Gui.ViewBase.ViewArrangement.Fixed;
            this.tbRelativeTo.CanFocus = true;
            this.tbRelativeTo.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyle.None;
            this.tbRelativeTo.Secret = false;
            this.tbRelativeTo.Data = "tbRelativeTo";
            this.tbRelativeTo.Text = "";
            this.tbRelativeTo.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Add(this.tbRelativeTo);
            this.lblSide.Width = 5;
            this.lblSide.Height = 1;
            this.lblSide.X = 23;
            this.lblSide.Y = 5;
            this.lblSide.Visible = true;
            this.lblSide.Arrangement = Terminal.Gui.ViewBase.ViewArrangement.Fixed;
            this.lblSide.CanFocus = false;
            this.lblSide.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyle.None;
            this.lblSide.Data = "lblSide";
            this.lblSide.Text = "Side:";
            this.lblSide.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Add(this.lblSide);
            this.rgSide.Width = 10;
            this.rgSide.Height = 4;
            this.rgSide.X = 30;
            this.rgSide.Y = 5;
            this.rgSide.Visible = true;
            this.rgSide.Arrangement = Terminal.Gui.ViewBase.ViewArrangement.Fixed;
            this.rgSide.CanFocus = true;
            this.rgSide.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyle.None;
            this.rgSide.Data = "rgSide";
            this.rgSide.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.rgSide.Labels = new string[] {
                    "Left",
                    "Top",
                    "Right",
                    "Bottom"};
            this.Add(this.rgSide);
            this.lblOffset.Width = 7;
            this.lblOffset.Height = 1;
            this.lblOffset.X = 21;
            this.lblOffset.Y = 9;
            this.lblOffset.Visible = true;
            this.lblOffset.Arrangement = Terminal.Gui.ViewBase.ViewArrangement.Fixed;
            this.lblOffset.CanFocus = false;
            this.lblOffset.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyle.None;
            this.lblOffset.Data = "lblOffset";
            this.lblOffset.Text = "Offset:";
            this.lblOffset.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Add(this.lblOffset);
            this.tbOffset.Width = 15;
            this.tbOffset.Height = 1;
            this.tbOffset.X = Pos.Right(lblOffset) + 1;
            this.tbOffset.Y = 9;
            this.tbOffset.Visible = true;
            this.tbOffset.Arrangement = Terminal.Gui.ViewBase.ViewArrangement.Fixed;
            this.tbOffset.CanFocus = true;
            this.tbOffset.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyle.None;
            this.tbOffset.Secret = false;
            this.tbOffset.Data = "tbOffset";
            this.tbOffset.Text = "";
            this.tbOffset.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Add(this.tbOffset);
            this.btnOk.Width = Dim.Auto();
            this.btnOk.Height = Dim.Auto();
            this.btnOk.X = 14;
            this.btnOk.Y = 11;
            this.btnOk.Visible = true;
            this.btnOk.Arrangement = Terminal.Gui.ViewBase.ViewArrangement.Fixed;
            this.btnOk.CanFocus = true;
            this.btnOk.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyle.Opaque;
            this.btnOk.Data = "btnOk";
            this.btnOk.Text = "Ok";
            this.btnOk.TextAlignment = Terminal.Gui.ViewBase.Alignment.Center;
            this.btnOk.IsDefault = true;
            this.Add(this.btnOk);
            this.btnCancel.Width = Dim.Auto();
            this.btnCancel.Height = Dim.Auto();
            this.btnCancel.X = 23;
            this.btnCancel.Y = 11;
            this.btnCancel.Visible = true;
            this.btnCancel.Arrangement = Terminal.Gui.ViewBase.ViewArrangement.Fixed;
            this.btnCancel.CanFocus = true;
            this.btnCancel.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyle.Opaque;
            this.btnCancel.Data = "btnCancel";
            this.btnCancel.Text = "Cancel";
            this.btnCancel.TextAlignment = Terminal.Gui.ViewBase.Alignment.Center;
            this.btnCancel.IsDefault = false;
            this.Add(this.btnCancel);
        }
    }
}
