
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.18.0
//      You can make changes to this file and they will not be overwritten when saving.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace TerminalGuiDesigner.UI.Windows
{
    using Terminal.Gui;

    public partial class SizeEditor
    {

        /// <summary>
        /// The users edited <see cref="Size"/> 
        /// </summary>
        public Size Result { get; private set; }
        public bool Cancelled { get; private set; }

        public SizeEditor(Size s)
        {
            InitializeComponent();
            Result = s;

            tfWidth.Text = s.Width.ToString();
            tfHeight.Text = s.Height.ToString();

            btnOk.Clicked += () =>
            {
                try
                {
                    Result = new Size(int.Parse(tfWidth.Text.ToString()), int.Parse(tfHeight.Text.ToString()));
                }
                catch (Exception ex)
                {
                    MessageBox.ErrorQuery("Bad Value", ex.Message);
                    return;
                }

                Cancelled = false;
                RequestStop();
            };

            btnCancel.Clicked += () =>
            {
                Cancelled = true;
                RequestStop();
            };
        }
    }
}
