
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.18.0
//      You can make changes to this file and they will not be overwritten when saving.
//  </auto-generated>
// -----------------------------------------------------------------------------

using Terminal.Gui.Views;

namespace TerminalGuiDesigner.UI.Windows;

using Terminal.Gui;
using Terminal.Gui.App;

/// <summary>
/// Popup editor for the <see cref="Size"/> class.
/// </summary>
public partial class SizeEditor : IValueGetterDialog
{
    private readonly IApplication app;

    /// <summary>
    /// The users edited <see cref="Size"/>
    /// </summary>
    public object? Result { get; private set; }

    /// <summary>
    /// True if user cancelled the dialog instead of hitting "Ok".
    /// </summary>
    public bool Cancelled { get; private set; }

    /// <summary>
    /// Creates a new instance of the <see cref="SizeEditor"/> class.
    /// </summary>
    /// <param name="app">The application instance.</param>
    /// <param name="s"></param>
    public SizeEditor(IApplication app, Size s)
    {
        this.app = app;
        InitializeComponent();
        Result = s;

        tfWidth.Text = s.Width.ToString();
        tfHeight.Text = s.Height.ToString();

        btnOk.Accepting += (s, e) =>
        {
            e.Handled = true;
            try
            {
                Result = new Size(int.Parse(tfWidth.Text.ToString()), int.Parse(tfHeight.Text.ToString()));
            }
            catch (Exception ex)
            {
                MessageBox.ErrorQuery(app, "Bad Value", ex.Message);
                return;
            }

            Cancelled = false;
            RequestStop();
        };

        btnCancel.Accepting += (s, e) =>
        {
            e.Handled = true;
            Cancelled = true;
            RequestStop();
        };
    }
}
