
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.1.0.0
//      You can make changes to this file and they will not be overwritten when saving.
//  </auto-generated>
// -----------------------------------------------------------------------------


using Terminal.Gui.App;
using Terminal.Gui.Input;
using Terminal.Gui.Views;

namespace TerminalGuiDesigner.UI.Windows {
    using System.Text;
    using Terminal.Gui.Text;

    public partial class SliderOptionEditor : IValueGetterDialog
    {
        private readonly IApplication app;
        private readonly Type genericTypeArgument;
        private readonly Type sliderOptionType;

        /// <summary>
        /// True if the dialog was canceled before completing
        /// </summary>
        public bool Cancelled { get; internal set; } = true;
        
        /// <summary>
        /// The resulting value as configured by the user
        /// </summary>
        public object ActualResult { get; internal set; }

        /// <summary>
        /// Creates a new instance of the Designer to create an instance of <see cref="SliderOption{T}"/>
        /// where T is of <see cref="Type"/> <paramref name="genericTypeArgument"/>.
        /// </summary>
        /// <param name="genericTypeArgument">The T Type of the <see cref="SliderOption{T}"/> you want to design</param>
        /// <param name="oldValue">Previous value (if editing an existing instance).</param>
        public SliderOptionEditor(IApplication app, Type genericTypeArgument, object? oldValue) {
            InitializeComponent();

            this.app = app;
            this.genericTypeArgument = genericTypeArgument;
            this.sliderOptionType = typeof(LinearRangeOption<>).MakeGenericType(this.genericTypeArgument);

            btnOk.Accepting += BtnOk_Clicked;
            btnCancel.Accepting += BtnCancel_Clicked;

            lblType.Text = $"({genericTypeArgument.Name})";

            if(oldValue != null)
            {
                var p = sliderOptionType.GetProperty("Legend");
                tfLegend.Text = (string)p.GetValue(oldValue);

                p = sliderOptionType.GetProperty("LegendAbbr");
                tfLegendAbbr.Text = ((Rune)p.GetValue(oldValue)).ToString();

                p = sliderOptionType.GetProperty("Data");

                if (this.genericTypeArgument == typeof(string))
                {
                    tfData.Text = (string)p.GetValue(oldValue);
                }
                else
                {
                    tfData.Text = p.GetValue(oldValue)?.ToString() ?? "";
                }
            }
        }

        private void BtnCancel_Clicked(object sender, CommandEventArgs e)
        {
            e.Handled = true;
            this.Cancelled = true;
            app.RequestStop();
        }

        private void BtnOk_Clicked(object sender, CommandEventArgs e)
        {
            e.Handled = true;
            try
            {
                this.BuildResult();
            }
            catch(Exception ex)
            {
                ExceptionViewer.ShowException(app, "Could not build result", ex);
                return;
            }

            this.Cancelled = false;
            app.RequestStop();
        }

        private void BuildResult()
        {
            ActualResult = Activator.CreateInstance(sliderOptionType);

            var p = sliderOptionType.GetProperty("Legend");
            p.SetValue(ActualResult, tfLegend.Text);

            if(tfLegendAbbr.Text.Length > 0)
            {
                p = sliderOptionType.GetProperty("LegendAbbr");
                p.SetValue(ActualResult, tfLegendAbbr.Text.ToRunes().First());
            }

            p = sliderOptionType.GetProperty("Data");

            if(this.genericTypeArgument == typeof(string))
            {
                p.SetValue(ActualResult, tfData.Text);
            }
            else
            {
                p.SetValue(ActualResult, Convert.ChangeType(tfData.Text, this.genericTypeArgument));
            }

        }
    }
}
