
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v2.0.0.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace TerminalGuiDesigner.UI.Windows {
    using System;
    using Terminal.Gui;
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Drawing;
    
    
    public partial class SliderOptionEditor : Terminal.Gui.Dialog {
        
        private Terminal.Gui.ColorScheme redOnBlack;
        
        private Terminal.Gui.ColorScheme tgDefault;
        
        private Terminal.Gui.Label label;
        
        private Terminal.Gui.TextField tfLegend;
        
        private Terminal.Gui.Label label2;
        
        private Terminal.Gui.TextField tfLegendAbbr;
        
        private Terminal.Gui.Label lblOneChar;
        
        private Terminal.Gui.Label label3;
        
        private Terminal.Gui.TextField tfData;
        
        private Terminal.Gui.Label lblType;
        
        private Terminal.Gui.Button btnOk;
        
        private Terminal.Gui.Button btnCancel;
        
        private void InitializeComponent() {
            this.btnCancel = new Terminal.Gui.Button();
            this.btnOk = new Terminal.Gui.Button();
            this.lblType = new Terminal.Gui.Label();
            this.tfData = new Terminal.Gui.TextField();
            this.label3 = new Terminal.Gui.Label();
            this.lblOneChar = new Terminal.Gui.Label();
            this.tfLegendAbbr = new Terminal.Gui.TextField();
            this.label2 = new Terminal.Gui.Label();
            this.tfLegend = new Terminal.Gui.TextField();
            this.label = new Terminal.Gui.Label();
            this.redOnBlack = new Terminal.Gui.ColorScheme(new Terminal.Gui.Attribute(4291104543u, 4278979596u), new Terminal.Gui.Attribute(4291104543u, 4286595104u), new Terminal.Gui.Attribute(4293347414u, 4278979596u), new Terminal.Gui.Attribute(4291611852u, 4278979596u), new Terminal.Gui.Attribute(4293347414u, 4286595104u));
            this.tgDefault = new Terminal.Gui.ColorScheme(new Terminal.Gui.Attribute(4294111986u, 4278204378u), new Terminal.Gui.Attribute(4278979596u, 4291611852u), new Terminal.Gui.Attribute(4284602070u, 4278204378u), new Terminal.Gui.Attribute(4286595104u, 4278204378u), new Terminal.Gui.Attribute(4282087679u, 4291611852u));
            this.Width = 50;
            this.Height = 10;
            this.X = Pos.Center();
            this.Y = Pos.Center();
            this.Visible = true;
            this.Arrangement = Terminal.Gui.ViewArrangement.Movable;
            this.Modal = true;
            this.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Title = "OptionEditor";
            this.label.Width = Dim.Auto();
            this.label.Height = 1;
            this.label.X = 6;
            this.label.Y = 0;
            this.label.Visible = true;
            this.label.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.label.Data = "label";
            this.label.Text = "Legend:";
            this.label.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.label);
            this.tfLegend.Width = Dim.Fill(0);
            this.tfLegend.Height = 1;
            this.tfLegend.X = 14;
            this.tfLegend.Y = 0;
            this.tfLegend.Visible = true;
            this.tfLegend.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.tfLegend.Secret = false;
            this.tfLegend.Data = "tfLegend";
            this.tfLegend.Text = "";
            this.tfLegend.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.tfLegend);
            this.label2.Width = Dim.Auto();
            this.label2.Height = 1;
            this.label2.X = 0;
            this.label2.Y = 1;
            this.label2.Visible = true;
            this.label2.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.label2.Data = "label2";
            this.label2.Text = "Abbreviation:";
            this.label2.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.label2);
            this.tfLegendAbbr.Width = 1;
            this.tfLegendAbbr.Height = 1;
            this.tfLegendAbbr.X = 14;
            this.tfLegendAbbr.Y = 1;
            this.tfLegendAbbr.Visible = true;
            this.tfLegendAbbr.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.tfLegendAbbr.Secret = false;
            this.tfLegendAbbr.Data = "tfLegendAbbr";
            this.tfLegendAbbr.Text = "";
            this.tfLegendAbbr.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.tfLegendAbbr);
            this.lblOneChar.Width = Dim.Auto();
            this.lblOneChar.Height = 1;
            this.lblOneChar.X = 0;
            this.lblOneChar.Y = 2;
            this.lblOneChar.Visible = true;
            this.lblOneChar.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.lblOneChar.Data = "lblOneChar";
            this.lblOneChar.Text = "(Single Char)  ";
            this.lblOneChar.TextAlignment = Terminal.Gui.Alignment.Center;
            this.Add(this.lblOneChar);
            this.label3.Width = Dim.Auto();
            this.label3.Height = 1;
            this.label3.X = 8;
            this.label3.Y = 3;
            this.label3.Visible = true;
            this.label3.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.label3.Data = "label3";
            this.label3.Text = "Data:";
            this.label3.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.label3);
            this.tfData.Width = Dim.Fill(0);
            this.tfData.Height = 1;
            this.tfData.X = 14;
            this.tfData.Y = 3;
            this.tfData.Visible = true;
            this.tfData.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.tfData.Secret = false;
            this.tfData.Data = "tfData";
            this.tfData.Text = "";
            this.tfData.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.tfData);
            this.lblType.Width = Dim.Fill(0);
            this.lblType.Height = Dim.Auto();
            this.lblType.X = -1;
            this.lblType.Y = 4;
            this.lblType.Visible = true;
            this.lblType.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.lblType.CanFocus = true;
            this.lblType.ShadowStyle = Terminal.Gui.ShadowStyle.None;
            this.lblType.Data = "lblType";
            this.lblType.Text = "( Type ) ";
            this.lblType.TextAlignment = Terminal.Gui.Alignment.Center;
            this.Add(this.lblType);
            this.btnOk.Width = Dim.Auto();
            this.btnOk.Height = Dim.Auto();
            this.btnOk.X = 10;
            this.btnOk.Y = 5;
            this.btnOk.Visible = true;
            this.btnOk.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.btnOk.CanFocus = true;
            this.btnOk.ShadowStyle = Terminal.Gui.ShadowStyle.Opaque;
            this.btnOk.Data = "btnOk";
            this.btnOk.Text = "Ok";
            this.btnOk.TextAlignment = Terminal.Gui.Alignment.Center;
            this.btnOk.IsDefault = true;
            this.Add(this.btnOk);
            this.btnCancel.Width = Dim.Auto();
            this.btnCancel.Height = Dim.Auto();
            this.btnCancel.X = 22;
            this.btnCancel.Y = 5;
            this.btnCancel.Visible = true;
            this.btnCancel.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.btnCancel.CanFocus = true;
            this.btnCancel.ShadowStyle = Terminal.Gui.ShadowStyle.Opaque;
            this.btnCancel.Data = "btnCancel";
            this.btnCancel.Text = "Cancel";
            this.btnCancel.TextAlignment = Terminal.Gui.Alignment.Center;
            this.btnCancel.IsDefault = false;
            this.Add(this.btnCancel);
        }
    }
}
