
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v2.2.2.1
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace Showcase {
    using System;
    using Terminal.Gui;
    using Terminal.Gui.App;
    using Terminal.Gui.Drawing;
    using Terminal.Gui.Input;
    using Terminal.Gui.ViewBase;
    using Terminal.Gui.Views;
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Drawing;
    
    
    public partial class Buttons : Terminal.Gui.ViewBase.View {
        
        private Terminal.Gui.Views.Button button;
        
        private Terminal.Gui.Views.Button button2;
        
        private Terminal.Gui.Views.Button button3;
        
        private Terminal.Gui.Views.Button button4;
        
        private Terminal.Gui.Views.Button button5;
        
        private Terminal.Gui.Views.Label label;
        
        private Terminal.Gui.Views.Button button6;
        
        private Terminal.Gui.Views.Button button7;
        
        private void InitializeComponent() {
            this.button7 = new Terminal.Gui.Views.Button();
            this.button6 = new Terminal.Gui.Views.Button();
            this.label = new Terminal.Gui.Views.Label();
            this.button5 = new Terminal.Gui.Views.Button();
            this.button4 = new Terminal.Gui.Views.Button();
            this.button3 = new Terminal.Gui.Views.Button();
            this.button2 = new Terminal.Gui.Views.Button();
            this.button = new Terminal.Gui.Views.Button();
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.Visible = true;
            this.CanFocus = false;
            this.ShadowStyle = null;
            this.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.button.Width = Dim.Auto();
            this.button.Height = Dim.Auto();
            this.button.X = 47;
            this.button.Y = 0;
            this.button.Visible = true;
            this.button.CanFocus = true;
            this.button.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyles.Opaque;
            this.button.Data = "button";
            this.button.Text = "Click _Me";
            this.button.TextAlignment = Terminal.Gui.ViewBase.Alignment.Center;
            this.button.IsDefault = false;
            this.Add(this.button);
            this.button2.Width = Dim.Auto();
            this.button2.Height = Dim.Auto();
            this.button2.X = 46;
            this.button2.Y = 2;
            this.button2.Visible = true;
            this.button2.CanFocus = true;
            this.button2.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyles.None;
            this.button2.Data = "button2";
            this.button2.Text = "Button without shadow";
            this.button2.TextAlignment = Terminal.Gui.ViewBase.Alignment.Center;
            this.button2.IsDefault = false;
            this.Add(this.button2);
            this.button3.Width = Dim.Auto();
            this.button3.Height = Dim.Auto();
            this.button3.X = 49;
            this.button3.Y = 4;
            this.button3.Visible = true;
            this.button3.CanFocus = true;
            this.button3.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyles.Opaque;
            this.button3.Data = "button3";
            this.button3.Text = "Default Button";
            this.button3.TextAlignment = Terminal.Gui.ViewBase.Alignment.Center;
            this.button3.IsDefault = true;
            this.Add(this.button3);
            this.button4.Width = 37;
            this.button4.Height = Dim.Auto();
            this.button4.X = 38;
            this.button4.Y = 6;
            this.button4.Visible = true;
            this.button4.CanFocus = true;
            this.button4.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyles.Opaque;
            this.button4.Data = "button4";
            this.button4.Text = "Fixed width button";
            this.button4.TextAlignment = Terminal.Gui.ViewBase.Alignment.Center;
            this.button4.IsDefault = false;
            this.Add(this.button4);
            this.button5.Width = Dim.Auto();
            this.button5.Height = Dim.Auto();
            this.button5.X = 42;
            this.button5.Y = 8;
            this.button5.Visible = true;
            this.button5.CanFocus = true;
            this.button5.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyles.Transparent;
            this.button5.Data = "button5";
            this.button5.Text = "Transparent shadow Button";
            this.button5.TextAlignment = Terminal.Gui.ViewBase.Alignment.Center;
            this.button5.IsDefault = false;
            this.Add(this.button5);
            this.label.Width = Dim.Fill(0);
            this.label.Height = Dim.Auto();
            this.label.X = 0;
            this.label.Y = 14;
            this.label.Visible = true;
            this.label.CanFocus = false;
            this.label.ShadowStyle = null;
            this.label.Data = "label";
            this.label.Text = ("Button Showcase\r\n------------------\r\n\r\nOne button can be IsDefault\r\nTab to button" +
                " and type to update label\r\nType underscore before a letter for \'alt\' hotkey\r\n\r\nS" +
                "hadowStyle defaults to Opaque\r\nWidth defaults to AutoSize");
            this.label.TextAlignment = Terminal.Gui.ViewBase.Alignment.Center;
            this.Add(this.label);
            this.button6.Width = Dim.Auto();
            this.button6.Height = Dim.Auto();
            this.button6.X = Pos.Percent(30);
            this.button6.Y = Pos.AnchorEnd(1);
            this.button6.Visible = true;
            this.button6.CanFocus = true;
            this.button6.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyles.Opaque;
            this.button6.Data = "button6";
            this.button6.Text = "Anchor End Button 1";
            this.button6.TextAlignment = Terminal.Gui.ViewBase.Alignment.Center;
            this.button6.IsDefault = false;
            this.Add(this.button6);
            this.button7.Width = Dim.Auto();
            this.button7.Height = Dim.Auto();
            this.button7.X = Pos.Right(button6) + 1;
            this.button7.Y = Pos.AnchorEnd(1);
            this.button7.Visible = true;
            this.button7.CanFocus = true;
            this.button7.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyles.Opaque;
            this.button7.Data = "button7";
            this.button7.Text = "Anchor End Button 2";
            this.button7.TextAlignment = Terminal.Gui.ViewBase.Alignment.Center;
            this.button7.IsDefault = false;
            this.Add(this.button7);
        }
    }
}
