
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v2.0.2.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace Showcase {
    using System;
    using Terminal.Gui;
    using Terminal.Gui.App;
    using Terminal.Gui.Drawing;
    using Terminal.Gui.Input;
    using Terminal.Gui.ViewBase;
    using Terminal.Gui.Views;
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Drawing;
    
    
    public partial class ColorPickers : Terminal.Gui.Views.Runnable {
        
        private Terminal.Gui.Views.ColorPicker colorPicker;
        
        private Terminal.Gui.Views.ColorPicker16 colorPicker16;
        
        private Terminal.Gui.Views.Label label;
        
        private Terminal.Gui.Views.Label label2;
        
        private void InitializeComponent() {
            this.label2 = new Terminal.Gui.Views.Label();
            this.label = new Terminal.Gui.Views.Label();
            this.colorPicker16 = new Terminal.Gui.Views.ColorPicker16();
            this.colorPicker = new Terminal.Gui.Views.ColorPicker();
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.Visible = true;
            this.CanFocus = true;
            this.ShadowStyle = null;
            this.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.colorPicker.Width = 47;
            this.colorPicker.Height = Dim.Auto();
            this.colorPicker.X = 16;
            this.colorPicker.Y = 3;
            this.colorPicker.Visible = true;
            this.colorPicker.CanFocus = true;
            this.colorPicker.ShadowStyle = null;
            this.colorPicker.Data = "colorPicker";
            this.colorPicker.Text = "#048B3A";
            this.colorPicker.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.colorPicker.Style.ColorModel = Terminal.Gui.Drawing.ColorModel.HSV;
            this.colorPicker.Style.ShowColorName = false;
            this.colorPicker.Style.ShowTextFields = true;
            this.colorPicker.ApplyStyleChanges();
            this.Add(this.colorPicker);
            this.colorPicker16.Width = Dim.Auto();
            this.colorPicker16.Height = Dim.Auto();
            this.colorPicker16.X = 76;
            this.colorPicker16.Y = 3;
            this.colorPicker16.Visible = true;
            this.colorPicker16.CanFocus = true;
            this.colorPicker16.ShadowStyle = null;
            this.colorPicker16.Data = "colorPicker16";
            this.colorPicker16.Text = "";
            this.colorPicker16.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Add(this.colorPicker16);
            this.label.Width = Dim.Auto();
            this.label.Height = Dim.Auto();
            this.label.X = 31;
            this.label.Y = 8;
            this.label.Visible = true;
            this.label.CanFocus = false;
            this.label.ShadowStyle = null;
            this.label.Data = "label";
            this.label.Text = "--ColorPicker--";
            this.label.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Add(this.label);
            this.label2.Width = Dim.Auto();
            this.label2.Height = Dim.Auto();
            this.label2.X = 83;
            this.label2.Y = 8;
            this.label2.Visible = true;
            this.label2.CanFocus = false;
            this.label2.ShadowStyle = null;
            this.label2.Data = "label2";
            this.label2.Text = "--ColorPicker16--";
            this.label2.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Add(this.label2);
        }
    }
}
