
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v2.0.2.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace Showcase {
    using System;
    using Terminal.Gui;
    using Terminal.Gui.App;
    using Terminal.Gui.Drawing;
    using Terminal.Gui.Input;
    using Terminal.Gui.ViewBase;
    using Terminal.Gui.Views;
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Drawing;
    
    
    public partial class DateTimes : Terminal.Gui.Views.Window {
        
        private Terminal.Gui.Views.Label label;
        
        private Terminal.Gui.Views.DateEditor dateEditor;
        
        private Terminal.Gui.Views.Label label3;
        
        private Terminal.Gui.Views.TimeEditor timeEditor;
        
        private Terminal.Gui.Views.Label label2;
        
        private Terminal.Gui.Views.DatePicker datePicker;
        
        private void InitializeComponent() {
            this.datePicker = new Terminal.Gui.Views.DatePicker();
            this.label2 = new Terminal.Gui.Views.Label();
            this.timeEditor = new Terminal.Gui.Views.TimeEditor();
            this.label3 = new Terminal.Gui.Views.Label();
            this.dateEditor = new Terminal.Gui.Views.DateEditor();

            this.label = new Terminal.Gui.Views.Label();
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.Visible = true;
            this.Arrangement = Terminal.Gui.ViewBase.ViewArrangement.Overlapped;
            this.CanFocus = true;
            this.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyles.None;
            this.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Title = "";
            this.label.Width = Dim.Auto();
            this.label.Height = Dim.Auto();
            this.label.X = 0;
            this.label.Y = 0;
            this.label.Visible = true;
            this.label.CanFocus = false;
            this.label.ShadowStyle = null;
            this.label.Data = "label";
            this.label.Text = "DateEditor:";
            this.label.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Add(this.label);
            this.dateEditor.Width = 10;
            this.dateEditor.Height = 1;
            this.dateEditor.X = 12;
            this.dateEditor.Y = 0;
            this.dateEditor.Visible = true;
            this.dateEditor.CanFocus = true;
            this.dateEditor.ShadowStyle = null;
            this.dateEditor.Data = "dateEditor";
            this.dateEditor.Text = "02/05/2026";
            this.dateEditor.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Add(this.dateEditor);
            this.label3.Width = Dim.Auto();
            this.label3.Height = Dim.Auto();
            this.label3.X = 24;
            this.label3.Y = 0;
            this.label3.Visible = true;
            this.label3.CanFocus = false;
            this.label3.ShadowStyle = null;
            this.label3.Data = "label3";
            this.label3.Text = "TimeEditor:";
            this.label3.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Add(this.label3);
            this.timeEditor.Width = 8;
            this.timeEditor.Height = 1;
            this.timeEditor.X = 36;
            this.timeEditor.Y = 0;
            this.timeEditor.Visible = true;
            this.timeEditor.CanFocus = true;
            this.timeEditor.ShadowStyle = null;
            this.timeEditor.Data = "timeEditor";
            this.timeEditor.Text = "00:00:00";
            this.timeEditor.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Add(this.timeEditor);
            this.label2.Width = Dim.Auto();
            this.label2.Height = Dim.Auto();
            this.label2.X = 0;
            this.label2.Y = 2;
            this.label2.Visible = true;
            this.label2.CanFocus = false;
            this.label2.ShadowStyle = null;
            this.label2.Data = "label2";
            this.label2.Text = "DatePicker:";
            this.label2.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Add(this.label2);
            this.datePicker.Width = Dim.Auto();
            this.datePicker.Height = Dim.Auto();
            this.datePicker.X = 0;
            this.datePicker.Y = 3;
            this.datePicker.Visible = true;
            this.datePicker.CanFocus = true;
            this.datePicker.ShadowStyle = null;
            this.datePicker.Data = "datePicker";
            this.datePicker.Text = "02/05/2026";
            this.datePicker.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Add(this.datePicker);
        }
    }
}
