
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v2.0.2.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace Showcase {
    using System;
    using Terminal.Gui;
    using Terminal.Gui.App;
    using Terminal.Gui.Drawing;
    using Terminal.Gui.Input;
    using Terminal.Gui.ViewBase;
    using Terminal.Gui.Views;
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Drawing;
    
    
    public partial class Lists : Terminal.Gui.ViewBase.View {
        
        private Terminal.Gui.Views.FrameView frameView;
        
        private Terminal.Gui.Views.DropDownList dropDownList;
        
        private Terminal.Gui.Views.FrameView frameView2;
        
        private Terminal.Gui.Views.ListView listView;
        
        private void InitializeComponent() {
            this.listView = new Terminal.Gui.Views.ListView();
            this.frameView2 = new Terminal.Gui.Views.FrameView();
            this.dropDownList = new Terminal.Gui.Views.DropDownList();
            this.frameView = new Terminal.Gui.Views.FrameView();
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.Visible = true;
            this.CanFocus = false;
            this.ShadowStyle = null;
            this.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.frameView.Width = 27;
            this.frameView.Height = 5;
            this.frameView.X = 0;
            this.frameView.Y = 0;
            this.frameView.Visible = true;
            this.frameView.Arrangement = Terminal.Gui.ViewBase.ViewArrangement.Fixed;
            this.frameView.CanFocus = true;
            this.frameView.ShadowStyle = null;
            this.frameView.Data = "frameView";
            this.frameView.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.frameView.Title = "DropDownList";
            this.Add(this.frameView);
            this.dropDownList.Width = 25;
            this.dropDownList.Height = 2;
            this.dropDownList.X = 0;
            this.dropDownList.Y = 0;
            this.dropDownList.Visible = true;
            this.dropDownList.CanFocus = true;
            this.dropDownList.ShadowStyle = null;
            this.dropDownList.Secret = false;
            this.dropDownList.Data = "dropDownList";
            this.dropDownList.Text = "";
            this.dropDownList.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.dropDownList.Source = new Terminal.Gui.Views.ListWrapper<string>(new System.Collections.ObjectModel.ObservableCollection<string>(new string[] {
                            "🐱 Cat",
                            "🐶 Dog",
                            "🐟 Fish"}));
            this.frameView.Add(this.dropDownList);
            this.frameView2.Width = 16;
            this.frameView2.Height = 5;
            this.frameView2.X = 27;
            this.frameView2.Y = 0;
            this.frameView2.Visible = true;
            this.frameView2.Arrangement = Terminal.Gui.ViewBase.ViewArrangement.Fixed;
            this.frameView2.CanFocus = true;
            this.frameView2.ShadowStyle = null;
            this.frameView2.Data = "frameView2";
            this.frameView2.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.frameView2.Title = "ListView";
            this.Add(this.frameView2);
            this.listView.Width = Dim.Fill(0);
            this.listView.Height = 3;
            this.listView.X = 0;
            this.listView.Y = 0;
            this.listView.Visible = true;
            this.listView.CanFocus = true;
            this.listView.ShadowStyle = null;
            this.listView.Data = "listView";
            this.listView.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.listView.Source = new Terminal.Gui.Views.ListWrapper<string>(new System.Collections.ObjectModel.ObservableCollection<string>(new string[] {
                            "🐱 Cat",
                            "🐶 Dog",
                            "🐟 Fish"}));
            this.frameView2.Add(this.listView);
        }
    }
}
