
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v2.0.0.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace Showcase
{
    using System;
    using Terminal.Gui;
    using Terminal.Gui.App;
    using Terminal.Gui.Drawing;
    using Terminal.Gui.Input;
    using Terminal.Gui.ViewBase;
    using Terminal.Gui.Views;
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Drawing;


    public partial class Menus : Terminal.Gui.Views.Dialog
    {

        private Terminal.Gui.Views.MenuBar menuBar;

        private Terminal.Gui.Views.MenuBarItem fileMenu;

        private Terminal.Gui.Views.MenuItem editMeMenuItem;

        private void InitializeComponent()
        {
            this.menuBar = new Terminal.Gui.Views.MenuBar();
            this.Width = Dim.Percent(90);
            this.Height = Dim.Percent(80);
            this.X = Pos.Center();
            this.Y = Pos.Center();
            this.Visible = true;
            this.Arrangement = Terminal.Gui.ViewBase.ViewArrangement.Overlapped;
            this.CanFocus = true;
            this.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyles.Transparent;
            this.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.menuBar.Width = Dim.Fill(0);
            this.menuBar.Height = Dim.Auto();
            this.menuBar.X = 0;
            this.menuBar.Y = 0;
            this.menuBar.Visible = true;
            this.menuBar.Arrangement = Terminal.Gui.ViewBase.ViewArrangement.Fixed;
            this.menuBar.CanFocus = false;
            this.menuBar.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyles.Transparent;
            this.menuBar.Data = "menuBar";
            this.menuBar.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.fileMenu = new Terminal.Gui.Views.MenuBarItem();
            this.fileMenu.Title = "_File";
            this.fileMenu.Key = Key.A;
            this.editMeMenuItem = new Terminal.Gui.Views.MenuItem();
            this.editMeMenuItem.Title = "Edit Me";
            this.editMeMenuItem.Data = "editMeMenuItem";
            this.fileMenu.PopoverMenu = new PopoverMenu([editMeMenuItem]);
            this.menuBar.Add(this.fileMenu);
            this.Add(this.menuBar);
        }
    }
}
