
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v2.0.0.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace Showcase {
    using System;
    using Terminal.Gui;
    using Terminal.Gui.App;
    using Terminal.Gui.Drawing;
    using Terminal.Gui.Input;
    using Terminal.Gui.ViewBase;
    using Terminal.Gui.Views;
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Drawing;
    
    
    public partial class Menus : Terminal.Gui.Views.Dialog {
        
        private Terminal.Gui.Views.MenuBar menuBar;
        
        private Terminal.Gui.Views.MenuBarItem fileMenu;
        
        private Terminal.Gui.Views.MenuItem newMenuItem;
        
        private Terminal.Gui.Views.MenuItem projectSolutionMenuItem;
        
        private Terminal.Gui.Views.MenuItem projectFromExistingCodeMenuItem;
        
        private Terminal.Gui.Views.MenuItem repositoryMenuItem;
        
        private Terminal.Gui.Views.MenuItem fileMenuItem;
        
        private Terminal.Gui.Views.MenuItem openMenuItem;
        
        private Terminal.Gui.Views.MenuItem projectSolutionMenuItem2;
        
        private Terminal.Gui.Views.MenuItem folderMenuItem;
        
        private Terminal.Gui.Views.MenuItem workspaceMenuItem;
        
        private Terminal.Gui.Views.MenuItem fileMenuItem2;
        
        private Terminal.Gui.Views.MenuItem cloneRepositoryMenuItem;
        
        private Terminal.Gui.Views.MenuItem startWindowMenuItem;
        
        private Terminal.Gui.Views.MenuItem addMenuItem;
        
        private Terminal.Gui.Views.MenuItem newProjectMenuItem;
        
        private Terminal.Gui.Views.MenuItem existingProjectMenuItem;
        
        private Terminal.Gui.Views.MenuItem existingWebSiteMenuItem;
        
        private Terminal.Gui.Views.MenuItem closeMenuItem;
        
        private Terminal.Gui.Views.MenuItem closeSolutionMenuItem;
        
        private Terminal.Gui.Views.MenuItem saveModalscsMenuItem;
        
        private Terminal.Gui.Views.MenuItem saveModalscsAsMenuItem;
        
        private Terminal.Gui.Views.MenuItem saveAllMenuItem;
        
        private Terminal.Gui.Views.MenuItem saveSolutionAsFilterMenuItem;
        
        private Terminal.Gui.Views.MenuItem pageSetupMenuItem;
        
        private Terminal.Gui.Views.MenuItem printMenuItem;
        
        private Terminal.Gui.Views.MenuItem accountSettingsMenuItem;
        
        private Terminal.Gui.Views.MenuItem moveModalscsIntoMenuItem;
        
        private Terminal.Gui.Views.MenuItem terminalGuiDesignerMenuItem;
        
        private Terminal.Gui.Views.MenuItem solutionItemsMenuItem;
        
        private Terminal.Gui.Views.MenuItem unitTestsMenuItem;
        
        private Terminal.Gui.Views.MenuItem recentFilesMenuItem;
        
        private Terminal.Gui.Views.MenuItem dReposTerminalGuiDesignerShowcaseMenuscsMenuItem;
        
        private Terminal.Gui.Views.MenuItem dReposTerminalGuiDesignerShowcaseMenusDesignercsMenuItem;
        
        private Terminal.Gui.Views.MenuItem dReposTerminalGuiDesignertestsMenuBarTestscsMenuItem;
        
        private Terminal.Gui.Views.MenuItem dMenuOperationsMoveMenuItemRightOperationcsMenuItem;
        
        private Terminal.Gui.Views.MenuItem dReposTerminalGuiDesignerShowcaseProgramcsMenuItem;
        
        private Terminal.Gui.Views.MenuItem dReposTerminalGuiDesignersrcUIEditorcsMenuItem;
        
        private Terminal.Gui.Views.MenuItem dReposTerminalGuiDesignersrcProgramcsMenuItem;
        
        private Terminal.Gui.Views.MenuItem dsrcbinDebugnet100MyViewDesignercsMenuItem;
        
        private Terminal.Gui.Views.MenuItem dTerminalGuiDesignersrcToCodeShadowStylePropertycsMenuItem;
        
        private Terminal.Gui.Views.MenuItem dReposTerminalGuiDesignersrcDesigncsMenuItem;
        
        private Terminal.Gui.Views.MenuItem recentProjectsAndSolutionsMenuItem;
        
        private Terminal.Gui.Views.MenuItem exitMenuItem;
        
        private Terminal.Gui.Views.MenuBarItem editMenu;
        
        private Terminal.Gui.Views.MenuItem goToMenuItem;
        
        private Terminal.Gui.Views.MenuItem findAndReplaceMenuItem;
        
        private Terminal.Gui.Views.MenuItem undoMenuItem;
        
        private Terminal.Gui.Views.MenuItem redoMenuItem;
        
        private Terminal.Gui.Views.MenuItem undoLastGlobalActionMenuItem;
        
        private Terminal.Gui.Views.MenuItem redoLastGlobalActionMenuItem;
        
        private Terminal.Gui.Views.MenuItem cutMenuItem;
        
        private Terminal.Gui.Views.MenuItem copyMenuItem;
        
        private Terminal.Gui.Views.MenuItem pasteMenuItem;
        
        private Terminal.Gui.Views.MenuItem deleteMenuItem;
        
        private Terminal.Gui.Views.MenuItem selectAllMenuItem;
        
        private Terminal.Gui.Views.MenuItem advancedMenuItem;
        
        private Terminal.Gui.Views.MenuItem bookmarksMenuItem;
        
        private Terminal.Gui.Views.MenuItem intelliSenseMenuItem;
        
        private Terminal.Gui.Views.MenuItem multipleCaretsMenuItem;
        
        private Terminal.Gui.Views.MenuBarItem viewMenu;
        
        private Terminal.Gui.Views.MenuItem editMeMenuItem;
        
        private Terminal.Gui.Views.MenuBarItem gitMenu;
        
        private Terminal.Gui.Views.MenuItem editMeMenuItem2;
        
        private Terminal.Gui.Views.MenuBarItem projectMenu;
        
        private Terminal.Gui.Views.MenuItem editMeMenuItem3;
        
        private Terminal.Gui.Views.MenuBarItem buildMenu;
        
        private Terminal.Gui.Views.MenuItem editMeMenuItem4;
        
        private Terminal.Gui.Views.MenuBarItem debugMenu;
        
        private Terminal.Gui.Views.MenuItem editMeMenuItem5;
        
        private Terminal.Gui.Views.MenuBarItem testMenu;
        
        private Terminal.Gui.Views.MenuItem editMeMenuItem6;
        
        private Terminal.Gui.Views.MenuBarItem toolsMenu;
        
        private Terminal.Gui.Views.MenuItem editMeMenuItem7;
        
        private Terminal.Gui.Views.MenuBarItem extensionsMenu;
        
        private Terminal.Gui.Views.MenuItem editMeMenuItem8;
        
        private Terminal.Gui.Views.MenuBarItem windowMenu;
        
        private Terminal.Gui.Views.MenuItem editMeMenuItem9;
        
        private Terminal.Gui.Views.MenuBarItem helpMenu;
        
        private Terminal.Gui.Views.MenuItem editMeMenuItem10;
        
        private void InitializeComponent() {
            this.menuBar = new Terminal.Gui.Views.MenuBar();
            this.Width = Dim.Percent(90);
            this.Height = Dim.Percent(80);
            this.X = Pos.Center();
            this.Y = Pos.Center();
            this.Visible = true;
            this.Arrangement = Terminal.Gui.ViewBase.ViewArrangement.Overlapped;
            this.CanFocus = true;
            this.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyles.Transparent;
            this.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.menuBar.Width = Dim.Fill(0);
            this.menuBar.Height = Dim.Auto();
            this.menuBar.X = 0;
            this.menuBar.Y = 0;
            this.menuBar.Visible = true;
            this.menuBar.Arrangement = Terminal.Gui.ViewBase.ViewArrangement.Fixed;
            this.menuBar.CanFocus = false;
            this.menuBar.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyles.None;
            this.menuBar.Data = "menuBar";
            this.menuBar.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.fileMenu = new Terminal.Gui.Views.MenuBarItem();
            this.fileMenu.Title = "_File";
            this.fileMenu.Key = new Key("F9");
            this.newMenuItem = new Terminal.Gui.Views.MenuItem();
            this.newMenuItem.Title = "New";
            this.projectSolutionMenuItem = new Terminal.Gui.Views.MenuItem();
            this.projectSolutionMenuItem.Title = "Project/Solution...";
            this.projectSolutionMenuItem.Key = new Key("N, CtrlMask, AltMask");
            this.projectFromExistingCodeMenuItem = new Terminal.Gui.Views.MenuItem();
            this.projectFromExistingCodeMenuItem.Title = "Project From Existing Code...";
            this.repositoryMenuItem = new Terminal.Gui.Views.MenuItem();
            this.repositoryMenuItem.Title = "Repository...";
            this.fileMenuItem = new Terminal.Gui.Views.MenuItem();
            this.fileMenuItem.Title = "File...";
            this.fileMenuItem.Key = new Key("N, CtrlMask");
            this.newMenuItem.SubMenu = new Menu([projectSolutionMenuItem,projectFromExistingCodeMenuItem,new Line { Orientation = Terminal.Gui.ViewBase.Orientation.Horizontal },repositoryMenuItem,new Line { Orientation = Terminal.Gui.ViewBase.Orientation.Horizontal },fileMenuItem]);
            this.openMenuItem = new Terminal.Gui.Views.MenuItem();
            this.openMenuItem.Title = "Open";
            this.projectSolutionMenuItem2 = new Terminal.Gui.Views.MenuItem();
            this.projectSolutionMenuItem2.Title = "Project/Solution...";
            this.projectSolutionMenuItem2.Key = new Key("O, CtrlMask");
            this.folderMenuItem = new Terminal.Gui.Views.MenuItem();
            this.folderMenuItem.Title = "Folder...";
            this.folderMenuItem.Key = new Key("O, CtrlMask, AltMask");
            this.workspaceMenuItem = new Terminal.Gui.Views.MenuItem();
            this.workspaceMenuItem.Title = "Workspace...";
            this.fileMenuItem2 = new Terminal.Gui.Views.MenuItem();
            this.fileMenuItem2.Title = "File...";
            this.fileMenuItem2.Key = new Key("O, CtrlMask");
            this.openMenuItem.SubMenu = new Menu([projectSolutionMenuItem2,new Line { Orientation = Terminal.Gui.ViewBase.Orientation.Horizontal },folderMenuItem,workspaceMenuItem,new Line { Orientation = Terminal.Gui.ViewBase.Orientation.Horizontal },fileMenuItem2]);
            this.cloneRepositoryMenuItem = new Terminal.Gui.Views.MenuItem();
            this.cloneRepositoryMenuItem.Title = "Clone Repository...";
            this.startWindowMenuItem = new Terminal.Gui.Views.MenuItem();
            this.startWindowMenuItem.Title = "Start Window";
            this.addMenuItem = new Terminal.Gui.Views.MenuItem();
            this.addMenuItem.Title = "Add";
            this.newProjectMenuItem = new Terminal.Gui.Views.MenuItem();
            this.newProjectMenuItem.Title = "New Project...";
            this.existingProjectMenuItem = new Terminal.Gui.Views.MenuItem();
            this.existingProjectMenuItem.Title = "Existing Project...";
            this.existingWebSiteMenuItem = new Terminal.Gui.Views.MenuItem();
            this.existingWebSiteMenuItem.Title = "Existing Web Site...";
            this.addMenuItem.SubMenu = new Menu([newProjectMenuItem,new Line { Orientation = Terminal.Gui.ViewBase.Orientation.Horizontal },existingProjectMenuItem,existingWebSiteMenuItem]);
            this.closeMenuItem = new Terminal.Gui.Views.MenuItem();
            this.closeMenuItem.Title = "Close";
            this.closeSolutionMenuItem = new Terminal.Gui.Views.MenuItem();
            this.closeSolutionMenuItem.Title = "Close Solution";
            this.saveModalscsMenuItem = new Terminal.Gui.Views.MenuItem();
            this.saveModalscsMenuItem.Title = "Save Modals.cs";
            this.saveModalscsMenuItem.Key = new Key("S, CtrlMask");
            this.saveModalscsAsMenuItem = new Terminal.Gui.Views.MenuItem();
            this.saveModalscsAsMenuItem.Title = "Save Modals.cs As...";
            this.saveAllMenuItem = new Terminal.Gui.Views.MenuItem();
            this.saveAllMenuItem.Title = "Save All";
            this.saveSolutionAsFilterMenuItem = new Terminal.Gui.Views.MenuItem();
            this.saveSolutionAsFilterMenuItem.Title = "Save Solution as Filter...";
            this.pageSetupMenuItem = new Terminal.Gui.Views.MenuItem();
            this.pageSetupMenuItem.Title = "Page Setup...";
            this.printMenuItem = new Terminal.Gui.Views.MenuItem();
            this.printMenuItem.Title = "Print...";
            this.accountSettingsMenuItem = new Terminal.Gui.Views.MenuItem();
            this.accountSettingsMenuItem.Title = "Account Settings...";
            this.moveModalscsIntoMenuItem = new Terminal.Gui.Views.MenuItem();
            this.moveModalscsIntoMenuItem.Title = "Move Modals.cs into";
            this.terminalGuiDesignerMenuItem = new Terminal.Gui.Views.MenuItem();
            this.terminalGuiDesignerMenuItem.Title = "1 TerminalGuiDesigner";
            this.solutionItemsMenuItem = new Terminal.Gui.Views.MenuItem();
            this.solutionItemsMenuItem.Title = "2 Solution Items";
            this.unitTestsMenuItem = new Terminal.Gui.Views.MenuItem();
            this.unitTestsMenuItem.Title = "3 UnitTests";
            this.moveModalscsIntoMenuItem.SubMenu = new Menu([terminalGuiDesignerMenuItem,solutionItemsMenuItem,unitTestsMenuItem]);
            this.recentFilesMenuItem = new Terminal.Gui.Views.MenuItem();
            this.recentFilesMenuItem.Title = "Recent Files";
            this.dReposTerminalGuiDesignerShowcaseMenuscsMenuItem = new Terminal.Gui.Views.MenuItem();
            this.dReposTerminalGuiDesignerShowcaseMenuscsMenuItem.Title = "1 D:\\Repos\\TerminalGuiDesigner\\Showcase\\Menus.cs";
            this.dReposTerminalGuiDesignerShowcaseMenusDesignercsMenuItem = new Terminal.Gui.Views.MenuItem();
            this.dReposTerminalGuiDesignerShowcaseMenusDesignercsMenuItem.Title = "2 D:\\Repos\\TerminalGuiDesigner\\Showcase\\Menus.Designer.cs";
            this.dReposTerminalGuiDesignertestsMenuBarTestscsMenuItem = new Terminal.Gui.Views.MenuItem();
            this.dReposTerminalGuiDesignertestsMenuBarTestscsMenuItem.Title = "3 D:\\Repos\\TerminalGuiDesigner\\tests\\MenuBarTests.cs";
            this.dMenuOperationsMoveMenuItemRightOperationcsMenuItem = new Terminal.Gui.Views.MenuItem();
            this.dMenuOperationsMoveMenuItemRightOperationcsMenuItem.Title = "4 D:\\...\\MenuOperations\\MoveMenuItemRightOperation.cs";
            this.dReposTerminalGuiDesignerShowcaseProgramcsMenuItem = new Terminal.Gui.Views.MenuItem();
            this.dReposTerminalGuiDesignerShowcaseProgramcsMenuItem.Title = "5 D:\\Repos\\TerminalGuiDesigner\\Showcase\\Program.cs";
            this.dReposTerminalGuiDesignersrcUIEditorcsMenuItem = new Terminal.Gui.Views.MenuItem();
            this.dReposTerminalGuiDesignersrcUIEditorcsMenuItem.Title = "6 D:\\Repos\\TerminalGuiDesigner\\src\\UI\\Editor.cs";
            this.dReposTerminalGuiDesignersrcProgramcsMenuItem = new Terminal.Gui.Views.MenuItem();
            this.dReposTerminalGuiDesignersrcProgramcsMenuItem.Title = "7 D:\\Repos\\TerminalGuiDesigner\\src\\Program.cs";
            this.dsrcbinDebugnet100MyViewDesignercsMenuItem = new Terminal.Gui.Views.MenuItem();
            this.dsrcbinDebugnet100MyViewDesignercsMenuItem.Title = "8 D:\\...\\src\\bin\\Debug\\net10.0\\MyView.Designer.cs";
            this.dTerminalGuiDesignersrcToCodeShadowStylePropertycsMenuItem = new Terminal.Gui.Views.MenuItem();
            this.dTerminalGuiDesignersrcToCodeShadowStylePropertycsMenuItem.Title = "9 D:\\...\\TerminalGuiDesigner\\src\\ToCode\\ShadowStyleProperty.cs";
            this.dReposTerminalGuiDesignersrcDesigncsMenuItem = new Terminal.Gui.Views.MenuItem();
            this.dReposTerminalGuiDesignersrcDesigncsMenuItem.Title = "10 D:\\Repos\\TerminalGuiDesigner\\src\\Design.cs";
            this.recentFilesMenuItem.SubMenu = new Menu([dReposTerminalGuiDesignerShowcaseMenuscsMenuItem,dReposTerminalGuiDesignerShowcaseMenusDesignercsMenuItem,dReposTerminalGuiDesignertestsMenuBarTestscsMenuItem,dMenuOperationsMoveMenuItemRightOperationcsMenuItem,dReposTerminalGuiDesignerShowcaseProgramcsMenuItem,dReposTerminalGuiDesignersrcUIEditorcsMenuItem,dReposTerminalGuiDesignersrcProgramcsMenuItem,dsrcbinDebugnet100MyViewDesignercsMenuItem,dTerminalGuiDesignersrcToCodeShadowStylePropertycsMenuItem,dReposTerminalGuiDesignersrcDesigncsMenuItem]);
            this.recentProjectsAndSolutionsMenuItem = new Terminal.Gui.Views.MenuItem();
            this.recentProjectsAndSolutionsMenuItem.Title = "Recent Projects and Solutions";
            this.exitMenuItem = new Terminal.Gui.Views.MenuItem();
            this.exitMenuItem.Title = "Exit";
            this.exitMenuItem.Key = new Key("X, CtrlMask");
            this.fileMenu.PopoverMenu = new PopoverMenu([newMenuItem,openMenuItem,cloneRepositoryMenuItem,startWindowMenuItem,new Line { Orientation = Terminal.Gui.ViewBase.Orientation.Horizontal },addMenuItem,new Line { Orientation = Terminal.Gui.ViewBase.Orientation.Horizontal },closeMenuItem,closeSolutionMenuItem,new Line { Orientation = Terminal.Gui.ViewBase.Orientation.Horizontal },saveModalscsMenuItem,saveModalscsAsMenuItem,saveAllMenuItem,saveSolutionAsFilterMenuItem,new Line { Orientation = Terminal.Gui.ViewBase.Orientation.Horizontal },pageSetupMenuItem,printMenuItem,new Line { Orientation = Terminal.Gui.ViewBase.Orientation.Horizontal },accountSettingsMenuItem,new Line { Orientation = Terminal.Gui.ViewBase.Orientation.Horizontal },moveModalscsIntoMenuItem,new Line { Orientation = Terminal.Gui.ViewBase.Orientation.Horizontal },recentFilesMenuItem,recentProjectsAndSolutionsMenuItem,new Line { Orientation = Terminal.Gui.ViewBase.Orientation.Horizontal },exitMenuItem]);
            this.menuBar.Add(this.fileMenu);
            this.editMenu = new Terminal.Gui.Views.MenuBarItem();
            this.editMenu.Title = "Edit";
            this.goToMenuItem = new Terminal.Gui.Views.MenuItem();
            this.goToMenuItem.Title = "Go To";
            this.findAndReplaceMenuItem = new Terminal.Gui.Views.MenuItem();
            this.findAndReplaceMenuItem.Title = "Find  and Replace";
            this.undoMenuItem = new Terminal.Gui.Views.MenuItem();
            this.undoMenuItem.Title = "Undo";
            this.redoMenuItem = new Terminal.Gui.Views.MenuItem();
            this.redoMenuItem.Title = "Redo";
            this.undoLastGlobalActionMenuItem = new Terminal.Gui.Views.MenuItem();
            this.undoLastGlobalActionMenuItem.Title = "Undo Last Global Action";
            this.redoLastGlobalActionMenuItem = new Terminal.Gui.Views.MenuItem();
            this.redoLastGlobalActionMenuItem.Title = "Redo Last Global Action";
            this.cutMenuItem = new Terminal.Gui.Views.MenuItem();
            this.cutMenuItem.Title = "Cut";
            this.copyMenuItem = new Terminal.Gui.Views.MenuItem();
            this.copyMenuItem.Title = "Copy";
            this.pasteMenuItem = new Terminal.Gui.Views.MenuItem();
            this.pasteMenuItem.Title = "Paste";
            this.deleteMenuItem = new Terminal.Gui.Views.MenuItem();
            this.deleteMenuItem.Title = "Delete";
            this.selectAllMenuItem = new Terminal.Gui.Views.MenuItem();
            this.selectAllMenuItem.Title = "Select All";
            this.advancedMenuItem = new Terminal.Gui.Views.MenuItem();
            this.advancedMenuItem.Title = "Advanced";
            this.bookmarksMenuItem = new Terminal.Gui.Views.MenuItem();
            this.bookmarksMenuItem.Title = "Bookmarks";
            this.intelliSenseMenuItem = new Terminal.Gui.Views.MenuItem();
            this.intelliSenseMenuItem.Title = "IntelliSense";
            this.multipleCaretsMenuItem = new Terminal.Gui.Views.MenuItem();
            this.multipleCaretsMenuItem.Title = "Multiple Carets";
            this.editMenu.PopoverMenu = new PopoverMenu([goToMenuItem,findAndReplaceMenuItem,new Line { Orientation = Terminal.Gui.ViewBase.Orientation.Horizontal },undoMenuItem,redoMenuItem,undoLastGlobalActionMenuItem,redoLastGlobalActionMenuItem,new Line { Orientation = Terminal.Gui.ViewBase.Orientation.Horizontal },cutMenuItem,copyMenuItem,pasteMenuItem,deleteMenuItem,new Line { Orientation = Terminal.Gui.ViewBase.Orientation.Horizontal },selectAllMenuItem,new Line { Orientation = Terminal.Gui.ViewBase.Orientation.Horizontal },advancedMenuItem,bookmarksMenuItem,intelliSenseMenuItem,multipleCaretsMenuItem]);
            this.menuBar.Add(this.editMenu);
            this.viewMenu = new Terminal.Gui.Views.MenuBarItem();
            this.viewMenu.Title = "View";
            this.editMeMenuItem = new Terminal.Gui.Views.MenuItem();
            this.editMeMenuItem.Title = "Edit Me";
            this.viewMenu.PopoverMenu = new PopoverMenu([editMeMenuItem]);
            this.menuBar.Add(this.viewMenu);
            this.gitMenu = new Terminal.Gui.Views.MenuBarItem();
            this.gitMenu.Title = "Git";
            this.editMeMenuItem2 = new Terminal.Gui.Views.MenuItem();
            this.editMeMenuItem2.Title = "Edit Me";
            this.gitMenu.PopoverMenu = new PopoverMenu([editMeMenuItem2]);
            this.menuBar.Add(this.gitMenu);
            this.projectMenu = new Terminal.Gui.Views.MenuBarItem();
            this.projectMenu.Title = "Project";
            this.editMeMenuItem3 = new Terminal.Gui.Views.MenuItem();
            this.editMeMenuItem3.Title = "Edit Me";
            this.projectMenu.PopoverMenu = new PopoverMenu([editMeMenuItem3]);
            this.menuBar.Add(this.projectMenu);
            this.buildMenu = new Terminal.Gui.Views.MenuBarItem();
            this.buildMenu.Title = "Build";
            this.editMeMenuItem4 = new Terminal.Gui.Views.MenuItem();
            this.editMeMenuItem4.Title = "Edit Me";
            this.buildMenu.PopoverMenu = new PopoverMenu([editMeMenuItem4]);
            this.menuBar.Add(this.buildMenu);
            this.debugMenu = new Terminal.Gui.Views.MenuBarItem();
            this.debugMenu.Title = "Debug";
            this.editMeMenuItem5 = new Terminal.Gui.Views.MenuItem();
            this.editMeMenuItem5.Title = "Edit Me";
            this.debugMenu.PopoverMenu = new PopoverMenu([editMeMenuItem5]);
            this.menuBar.Add(this.debugMenu);
            this.testMenu = new Terminal.Gui.Views.MenuBarItem();
            this.testMenu.Title = "Test";
            this.editMeMenuItem6 = new Terminal.Gui.Views.MenuItem();
            this.editMeMenuItem6.Title = "Edit Me";
            this.testMenu.PopoverMenu = new PopoverMenu([editMeMenuItem6]);
            this.menuBar.Add(this.testMenu);
            this.toolsMenu = new Terminal.Gui.Views.MenuBarItem();
            this.toolsMenu.Title = "Tools";
            this.editMeMenuItem7 = new Terminal.Gui.Views.MenuItem();
            this.editMeMenuItem7.Title = "Edit Me";
            this.toolsMenu.PopoverMenu = new PopoverMenu([editMeMenuItem7]);
            this.menuBar.Add(this.toolsMenu);
            this.extensionsMenu = new Terminal.Gui.Views.MenuBarItem();
            this.extensionsMenu.Title = "Extensions";
            this.editMeMenuItem8 = new Terminal.Gui.Views.MenuItem();
            this.editMeMenuItem8.Title = "Edit Me";
            this.extensionsMenu.PopoverMenu = new PopoverMenu([editMeMenuItem8]);
            this.menuBar.Add(this.extensionsMenu);
            this.windowMenu = new Terminal.Gui.Views.MenuBarItem();
            this.windowMenu.Title = "Window";
            this.editMeMenuItem9 = new Terminal.Gui.Views.MenuItem();
            this.editMeMenuItem9.Title = "Edit Me";
            this.windowMenu.PopoverMenu = new PopoverMenu([editMeMenuItem9]);
            this.menuBar.Add(this.windowMenu);
            this.helpMenu = new Terminal.Gui.Views.MenuBarItem();
            this.helpMenu.Title = "Help";
            this.editMeMenuItem10 = new Terminal.Gui.Views.MenuItem();
            this.editMeMenuItem10.Title = "Edit Me";
            this.helpMenu.PopoverMenu = new PopoverMenu([editMeMenuItem10]);
            this.menuBar.Add(this.helpMenu);
            this.Add(this.menuBar);
        }
    }
}
