
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v2.0.0.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace Showcase {
    using System;
    using Terminal.Gui;
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Drawing;
    
    
    public partial class Menu : Terminal.Gui.Window {
        
        private Terminal.Gui.TextField textField;
        
        private Terminal.Gui.MenuBar menuBar;
        
        private Terminal.Gui.MenuBarItem fileF9Menu;
        
        private Terminal.Gui.MenuBarItem newMenu;
        
        private Terminal.Gui.MenuItem projectMenuItem;
        
        private Terminal.Gui.MenuItem repositoryMenuItem;
        
        private Terminal.Gui.MenuItem fileMenuItem;
        
        private Terminal.Gui.MenuItem projectFromExistingCodeMenuItem;
        
        private Terminal.Gui.MenuItem spellCheckerConfigurationForSelectedItemMenuItem;
        
        private void InitializeComponent() {
            this.menuBar = new Terminal.Gui.MenuBar();
            this.textField = new Terminal.Gui.TextField();
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.Visible = true;
            this.Arrangement = Terminal.Gui.ViewArrangement.Overlapped;
            this.CanFocus = true;
            this.ShadowStyle = Terminal.Gui.ShadowStyle.None;
            this.Modal = false;
            this.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Title = "";
            this.textField.Width = 5;
            this.textField.Height = 1;
            this.textField.X = 0;
            this.textField.Y = 6;
            this.textField.Visible = true;
            this.textField.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.textField.CanFocus = true;
            this.textField.ShadowStyle = Terminal.Gui.ShadowStyle.None;
            this.textField.Secret = false;
            this.textField.Data = "textField";
            this.textField.Text = "Heya";
            this.textField.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.textField);
            this.menuBar.Width = Dim.Fill(0);
            this.menuBar.Height = 1;
            this.menuBar.X = 0;
            this.menuBar.Y = 0;
            this.menuBar.Visible = true;
            this.menuBar.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.menuBar.CanFocus = false;
            this.menuBar.ShadowStyle = Terminal.Gui.ShadowStyle.None;
            this.menuBar.Data = "menuBar";
            this.menuBar.TextAlignment = Terminal.Gui.Alignment.Start;
            this.fileF9Menu = new Terminal.Gui.MenuBarItem();
            this.fileF9Menu.Title = "_File (F9)";
            this.newMenu = new Terminal.Gui.MenuBarItem();
            this.newMenu.Title = "New";
            this.projectMenuItem = new Terminal.Gui.MenuItem();
            this.projectMenuItem.Title = "Project...";
            this.projectMenuItem.Data = "projectMenuItem";
            this.projectMenuItem.ShortcutKey = ((Terminal.Gui.KeyCode)(1342177358u));
            this.repositoryMenuItem = new Terminal.Gui.MenuItem();
            this.repositoryMenuItem.Title = "Repository...";
            this.repositoryMenuItem.Data = "repositoryMenuItem";
            this.fileMenuItem = new Terminal.Gui.MenuItem();
            this.fileMenuItem.Title = "File...";
            this.fileMenuItem.Data = "fileMenuItem";
            this.projectFromExistingCodeMenuItem = new Terminal.Gui.MenuItem();
            this.projectFromExistingCodeMenuItem.Title = "Project From Existing Code...";
            this.projectFromExistingCodeMenuItem.Data = "projectFromExistingCodeMenuItem";
            this.spellCheckerConfigurationForSelectedItemMenuItem = new Terminal.Gui.MenuItem();
            this.spellCheckerConfigurationForSelectedItemMenuItem.Title = "Spell Checker Configuration for Selected Item";
            this.spellCheckerConfigurationForSelectedItemMenuItem.Data = "spellCheckerConfigurationForSelectedItemMenuItem";
            this.newMenu.Children = new Terminal.Gui.MenuItem[] {
                    this.projectMenuItem,
                    this.repositoryMenuItem,
                    this.fileMenuItem,
                    this.projectFromExistingCodeMenuItem,
                    null,
                    this.spellCheckerConfigurationForSelectedItemMenuItem};
            this.fileF9Menu.Children = new Terminal.Gui.MenuItem[] {
                    this.newMenu};
            this.menuBar.Menus = new Terminal.Gui.MenuBarItem[] {
                    this.fileF9Menu};
            this.Add(this.menuBar);
        }
    }
}
