
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v2.0.0.0
//      You can make changes to this file and they will not be overwritten when saving.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace Showcase {
    using Terminal.Gui;
    
    
    public partial class Menu {
        
        public Menu() {
            InitializeComponent();
        }
    }
}
