
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v2.0.2.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace Showcase {
    using System;
    using Terminal.Gui;
    using Terminal.Gui.App;
    using Terminal.Gui.Drawing;
    using Terminal.Gui.Input;
    using Terminal.Gui.ViewBase;
    using Terminal.Gui.Views;
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Drawing;
    
    
    public partial class Numbers : Terminal.Gui.Views.Dialog {
        
        private Terminal.Gui.Views.Label label;
        
        private Terminal.Gui.Views.NumericUpDown numericUpDown;
        
        private Terminal.Gui.Views.Label label2;
        
        private Terminal.Gui.Views.NumericUpDown<decimal> numericUpDown1;
        
        private Terminal.Gui.Views.Label label3;
        
        private Terminal.Gui.Views.NumericUpDown<double> numericUpDown2;
        
        private Terminal.Gui.Views.Label label4;
        
        private Terminal.Gui.Views.NumericUpDown<int> numericUpDown3;
        
        private Terminal.Gui.Views.Label label5;
        
        private Terminal.Gui.Views.NumericUpDown<long> numericUpDown4;
        
        private Terminal.Gui.Views.Label label6;
        
        private Terminal.Gui.Views.NumericUpDown<float> numericUpDown5;
        
        private Terminal.Gui.Views.Label label7;
        
        private Terminal.Gui.Views.ProgressBar progressBar;
        
        private Terminal.Gui.Views.SpinnerView spinnerView;
        
        private void InitializeComponent() {
            this.spinnerView = new Terminal.Gui.Views.SpinnerView();
            this.progressBar = new Terminal.Gui.Views.ProgressBar();
            this.label7 = new Terminal.Gui.Views.Label();
            this.numericUpDown5 = new Terminal.Gui.Views.NumericUpDown<float>();
            this.label6 = new Terminal.Gui.Views.Label();
            this.numericUpDown4 = new Terminal.Gui.Views.NumericUpDown<long>();
            this.label5 = new Terminal.Gui.Views.Label();
            this.numericUpDown3 = new Terminal.Gui.Views.NumericUpDown<int>();
            this.label4 = new Terminal.Gui.Views.Label();
            this.numericUpDown2 = new Terminal.Gui.Views.NumericUpDown<double>();
            this.label3 = new Terminal.Gui.Views.Label();
            this.numericUpDown1 = new Terminal.Gui.Views.NumericUpDown<decimal>();
            this.label2 = new Terminal.Gui.Views.Label();
            this.numericUpDown = new Terminal.Gui.Views.NumericUpDown();
            this.label = new Terminal.Gui.Views.Label();
            this.Width = Dim.Percent(90);
            this.Height = Dim.Percent(80);
            this.X = Pos.Center();
            this.Y = Pos.Center();
            this.Visible = true;
            this.CanFocus = true;
            this.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyles.Transparent;
            this.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.label.Width = Dim.Auto();
            this.label.Height = Dim.Auto();
            this.label.X = 0;
            this.label.Y = 0;
            this.label.Visible = true;
            this.label.CanFocus = false;
            this.label.ShadowStyle = null;
            this.label.Data = "label";
            this.label.Text = "NumericUpDown";
            this.label.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Add(this.label);
            this.numericUpDown.Width = 8;
            this.numericUpDown.Height = 1;
            this.numericUpDown.X = 23;
            this.numericUpDown.Y = 0;
            this.numericUpDown.Visible = true;
            this.numericUpDown.CanFocus = true;
            this.numericUpDown.ShadowStyle = null;
            this.numericUpDown.Data = "numericUpDown";
            this.numericUpDown.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.numericUpDown.Value = 0;
            this.numericUpDown.Increment = 1;
            this.Add(this.numericUpDown);
            this.label2.Width = Dim.Auto();
            this.label2.Height = Dim.Auto();
            this.label2.X = 0;
            this.label2.Y = 1;
            this.label2.Visible = true;
            this.label2.CanFocus = false;
            this.label2.ShadowStyle = null;
            this.label2.Data = "label2";
            this.label2.Text = "NumericUpDown<Decimal>";
            this.label2.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Add(this.label2);
            this.numericUpDown1.Width = Dim.Auto();
            this.numericUpDown1.Height = Dim.Auto();
            this.numericUpDown1.X = 23;
            this.numericUpDown1.Y = 1;
            this.numericUpDown1.Visible = true;
            this.numericUpDown1.CanFocus = true;
            this.numericUpDown1.ShadowStyle = null;
            this.numericUpDown1.Data = "numericUpDown1";
            this.numericUpDown1.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.numericUpDown1.Value = 11.1m;
            this.numericUpDown1.Increment = 0.001m;
            this.Add(this.numericUpDown1);
            this.label3.Width = Dim.Auto();
            this.label3.Height = Dim.Auto();
            this.label3.X = 0;
            this.label3.Y = 2;
            this.label3.Visible = true;
            this.label3.CanFocus = false;
            this.label3.ShadowStyle = null;
            this.label3.Data = "label3";
            this.label3.Text = "NumericUpDown<Double>";
            this.label3.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Add(this.label3);
            this.numericUpDown2.Width = Dim.Auto();
            this.numericUpDown2.Height = Dim.Auto();
            this.numericUpDown2.X = 23;
            this.numericUpDown2.Y = 2;
            this.numericUpDown2.Visible = true;
            this.numericUpDown2.CanFocus = true;
            this.numericUpDown2.ShadowStyle = null;
            this.numericUpDown2.Data = "numericUpDown2";
            this.numericUpDown2.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.numericUpDown2.Value = 12.3D;
            this.numericUpDown2.Increment = 0.1D;
            this.Add(this.numericUpDown2);
            this.label4.Width = Dim.Auto();
            this.label4.Height = Dim.Auto();
            this.label4.X = 0;
            this.label4.Y = 3;
            this.label4.Visible = true;
            this.label4.CanFocus = false;
            this.label4.ShadowStyle = null;
            this.label4.Data = "label4";
            this.label4.Text = "NumericUpDown<Int32>";
            this.label4.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Add(this.label4);
            this.numericUpDown3.Width = Dim.Auto();
            this.numericUpDown3.Height = Dim.Auto();
            this.numericUpDown3.X = 23;
            this.numericUpDown3.Y = 3;
            this.numericUpDown3.Visible = true;
            this.numericUpDown3.CanFocus = true;
            this.numericUpDown3.ShadowStyle = null;
            this.numericUpDown3.Data = "numericUpDown3";
            this.numericUpDown3.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.numericUpDown3.Value = 12312321;
            this.numericUpDown3.Increment = 1;
            this.Add(this.numericUpDown3);
            this.label5.Width = Dim.Auto();
            this.label5.Height = Dim.Auto();
            this.label5.X = 0;
            this.label5.Y = 4;
            this.label5.Visible = true;
            this.label5.CanFocus = false;
            this.label5.ShadowStyle = null;
            this.label5.Data = "label5";
            this.label5.Text = "NumericUpDown<Int64>";
            this.label5.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Add(this.label5);
            this.numericUpDown4.Width = Dim.Auto();
            this.numericUpDown4.Height = Dim.Auto();
            this.numericUpDown4.X = 23;
            this.numericUpDown4.Y = 4;
            this.numericUpDown4.Visible = true;
            this.numericUpDown4.CanFocus = true;
            this.numericUpDown4.ShadowStyle = null;
            this.numericUpDown4.Data = "numericUpDown4";
            this.numericUpDown4.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.numericUpDown4.Value = 6147483647;
            this.numericUpDown4.Increment = 10000000000;
            this.Add(this.numericUpDown4);
            this.label6.Width = Dim.Auto();
            this.label6.Height = Dim.Auto();
            this.label6.X = 0;
            this.label6.Y = 5;
            this.label6.Visible = true;
            this.label6.CanFocus = false;
            this.label6.ShadowStyle = null;
            this.label6.Data = "label6";
            this.label6.Text = "NumericUpDown<Single>";
            this.label6.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Add(this.label6);
            this.numericUpDown5.Width = Dim.Auto();
            this.numericUpDown5.Height = Dim.Auto();
            this.numericUpDown5.X = 23;
            this.numericUpDown5.Y = 5;
            this.numericUpDown5.Visible = true;
            this.numericUpDown5.CanFocus = true;
            this.numericUpDown5.ShadowStyle = null;
            this.numericUpDown5.Data = "numericUpDown5";
            this.numericUpDown5.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.numericUpDown5.Value = 0F;
            this.numericUpDown5.Increment = 1F;
            this.Add(this.numericUpDown5);
            this.label7.Width = Dim.Auto();
            this.label7.Height = Dim.Auto();
            this.label7.X = 0;
            this.label7.Y = 7;
            this.label7.Visible = true;
            this.label7.CanFocus = false;
            this.label7.ShadowStyle = null;
            this.label7.Data = "label7";
            this.label7.Text = "ProgressBar with Spinner";
            this.label7.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Add(this.label7);
            this.progressBar.Width = 95;
            this.progressBar.Height = 1;
            this.progressBar.X = 0;
            this.progressBar.Y = 8;
            this.progressBar.Visible = true;
            this.progressBar.CanFocus = false;
            this.progressBar.ShadowStyle = null;
            this.progressBar.Data = "progressBar";
            this.progressBar.Text = "100%";
            this.progressBar.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.progressBar.Fraction = 1F;
            this.progressBar.BidirectionalMarquee = true;
            this.progressBar.ProgressBarStyle = Terminal.Gui.Views.ProgressBarStyle.MarqueeBlocks;
            this.progressBar.ProgressBarFormat = Terminal.Gui.Views.ProgressBarFormat.Simple;
            this.progressBar.SegmentCharacter = new System.Text.Rune('▌');
            this.Add(this.progressBar);
            this.spinnerView.Width = 1;
            this.spinnerView.Height = Dim.Auto();
            this.spinnerView.X = 95;
            this.spinnerView.Y = 8;
            this.spinnerView.Visible = true;
            this.spinnerView.CanFocus = false;
            this.spinnerView.ShadowStyle = null;
            this.spinnerView.AutoSpin = true;
            this.spinnerView.Style = new Terminal.Gui.Views.SpinnerStyle.Line();
            this.spinnerView.Data = "spinnerView";
            this.spinnerView.Text = "";
            this.spinnerView.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Add(this.spinnerView);
        }
    }
}
