
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v2.0.0.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace Showcase {
    using System;
    using Terminal.Gui;
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Drawing;
    
    
    public partial class NumericUpDown : Terminal.Gui.Window {
        
        private Terminal.Gui.Label lblInt;
        
        private Terminal.Gui.NumericUpDown<int> numericUpDownInt;
        
        private Terminal.Gui.Label lblInt64;
        
        private Terminal.Gui.NumericUpDown<long> numericUpDownInt64;
        
        private Terminal.Gui.Label label3;
        
        private Terminal.Gui.NumericUpDown<double> numericUpDown2;
        
        private Terminal.Gui.Label label6;
        
        private Terminal.Gui.NumericUpDown<float> numericUpDownSingle;
        
        private Terminal.Gui.Label label;
        
        private Terminal.Gui.NumericUpDown<decimal> numericUpDownDecimal;
        
        private Terminal.Gui.Label label4;
        
        private Terminal.Gui.NumericUpDown<float> numericUpDown3;
        
        private Terminal.Gui.Label label5;
        
        private void InitializeComponent() {
            this.label5 = new Terminal.Gui.Label();
            this.numericUpDown3 = new Terminal.Gui.NumericUpDown<float>();
            this.label4 = new Terminal.Gui.Label();
            this.numericUpDownDecimal = new Terminal.Gui.NumericUpDown<decimal>();
            this.label = new Terminal.Gui.Label();
            this.numericUpDownSingle = new Terminal.Gui.NumericUpDown<float>();
            this.label6 = new Terminal.Gui.Label();
            this.numericUpDown2 = new Terminal.Gui.NumericUpDown<double>();
            this.label3 = new Terminal.Gui.Label();
            this.numericUpDownInt64 = new Terminal.Gui.NumericUpDown<long>();
            this.lblInt64 = new Terminal.Gui.Label();
            this.numericUpDownInt = new Terminal.Gui.NumericUpDown<int>();
            this.lblInt = new Terminal.Gui.Label();
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.Visible = true;
            this.Arrangement = (Terminal.Gui.ViewArrangement.Movable | Terminal.Gui.ViewArrangement.Overlapped);
            this.CanFocus = true;
            this.ShadowStyle = Terminal.Gui.ShadowStyle.None;
            this.Modal = false;
            this.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Title = "Numeric Up Down Controls";
            this.lblInt.Width = Dim.Auto();
            this.lblInt.Height = 1;
            this.lblInt.X = 0;
            this.lblInt.Y = 0;
            this.lblInt.Visible = true;
            this.lblInt.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.lblInt.CanFocus = true;
            this.lblInt.ShadowStyle = Terminal.Gui.ShadowStyle.None;
            this.lblInt.Data = "lblInt";
            this.lblInt.Text = "Int:";
            this.lblInt.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.lblInt);
            this.numericUpDownInt.Width = Dim.Auto();
            this.numericUpDownInt.Height = Dim.Auto();
            this.numericUpDownInt.X = 9;
            this.numericUpDownInt.Y = 0;
            this.numericUpDownInt.Visible = true;
            this.numericUpDownInt.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.numericUpDownInt.CanFocus = true;
            this.numericUpDownInt.ShadowStyle = Terminal.Gui.ShadowStyle.None;
            this.numericUpDownInt.Data = "numericUpDownInt";
            this.numericUpDownInt.TextAlignment = Terminal.Gui.Alignment.Start;
            this.numericUpDownInt.Value = 1;
            this.numericUpDownInt.Increment = 2;
            this.Add(this.numericUpDownInt);
            this.lblInt64.Width = Dim.Auto();
            this.lblInt64.Height = 1;
            this.lblInt64.X = 0;
            this.lblInt64.Y = 1;
            this.lblInt64.Visible = true;
            this.lblInt64.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.lblInt64.CanFocus = true;
            this.lblInt64.ShadowStyle = Terminal.Gui.ShadowStyle.None;
            this.lblInt64.Data = "lblInt64";
            this.lblInt64.Text = "Int64:";
            this.lblInt64.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.lblInt64);
            this.numericUpDownInt64.Width = Dim.Auto();
            this.numericUpDownInt64.Height = Dim.Auto();
            this.numericUpDownInt64.X = 9;
            this.numericUpDownInt64.Y = 1;
            this.numericUpDownInt64.Visible = true;
            this.numericUpDownInt64.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.numericUpDownInt64.CanFocus = true;
            this.numericUpDownInt64.ShadowStyle = Terminal.Gui.ShadowStyle.None;
            this.numericUpDownInt64.Data = "numericUpDownInt64";
            this.numericUpDownInt64.TextAlignment = Terminal.Gui.Alignment.Start;
            this.numericUpDownInt64.Value = 8943589458974;
            this.numericUpDownInt64.Increment = 1;
            this.Add(this.numericUpDownInt64);
            this.label3.Width = Dim.Auto();
            this.label3.Height = 1;
            this.label3.X = 0;
            this.label3.Y = 2;
            this.label3.Visible = true;
            this.label3.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.label3.CanFocus = true;
            this.label3.ShadowStyle = Terminal.Gui.ShadowStyle.None;
            this.label3.Data = "label3";
            this.label3.Text = "Double:";
            this.label3.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.label3);
            this.numericUpDown2.Width = Dim.Auto();
            this.numericUpDown2.Height = Dim.Auto();
            this.numericUpDown2.X = 9;
            this.numericUpDown2.Y = 2;
            this.numericUpDown2.Visible = true;
            this.numericUpDown2.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.numericUpDown2.CanFocus = true;
            this.numericUpDown2.ShadowStyle = Terminal.Gui.ShadowStyle.None;
            this.numericUpDown2.Data = "numericUpDown2";
            this.numericUpDown2.TextAlignment = Terminal.Gui.Alignment.Start;
            this.numericUpDown2.Value = 32.3D;
            this.numericUpDown2.Increment = 0.01D;
            this.Add(this.numericUpDown2);
            this.label6.Width = Dim.Auto();
            this.label6.Height = 1;
            this.label6.X = 0;
            this.label6.Y = 3;
            this.label6.Visible = true;
            this.label6.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.label6.CanFocus = true;
            this.label6.ShadowStyle = Terminal.Gui.ShadowStyle.None;
            this.label6.Data = "label6";
            this.label6.Text = "Single:";
            this.label6.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.label6);
            this.numericUpDownSingle.Width = Dim.Auto();
            this.numericUpDownSingle.Height = Dim.Auto();
            this.numericUpDownSingle.X = 9;
            this.numericUpDownSingle.Y = 3;
            this.numericUpDownSingle.Visible = true;
            this.numericUpDownSingle.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.numericUpDownSingle.CanFocus = true;
            this.numericUpDownSingle.ShadowStyle = Terminal.Gui.ShadowStyle.None;
            this.numericUpDownSingle.Data = "numericUpDownSingle";
            this.numericUpDownSingle.TextAlignment = Terminal.Gui.Alignment.Start;
            this.numericUpDownSingle.Value = 1F;
            this.numericUpDownSingle.Increment = 1F;
            this.Add(this.numericUpDownSingle);
            this.label.Width = Dim.Auto();
            this.label.Height = 1;
            this.label.X = 0;
            this.label.Y = 4;
            this.label.Visible = true;
            this.label.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.label.CanFocus = true;
            this.label.ShadowStyle = Terminal.Gui.ShadowStyle.None;
            this.label.Data = "label";
            this.label.Text = "Decimal:";
            this.label.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.label);
            this.numericUpDownDecimal.Width = Dim.Auto();
            this.numericUpDownDecimal.Height = Dim.Auto();
            this.numericUpDownDecimal.X = 9;
            this.numericUpDownDecimal.Y = 4;
            this.numericUpDownDecimal.Visible = true;
            this.numericUpDownDecimal.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.numericUpDownDecimal.CanFocus = true;
            this.numericUpDownDecimal.ShadowStyle = Terminal.Gui.ShadowStyle.None;
            this.numericUpDownDecimal.Data = "numericUpDownDecimal";
            this.numericUpDownDecimal.TextAlignment = Terminal.Gui.Alignment.Start;
            this.numericUpDownDecimal.Value = 0.00000000001m;
            this.numericUpDownDecimal.Increment = 0.00000000000001m;
            this.Add(this.numericUpDownDecimal);
            this.label4.Width = Dim.Auto();
            this.label4.Height = 1;
            this.label4.X = 0;
            this.label4.Y = 7;
            this.label4.Visible = true;
            this.label4.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.label4.CanFocus = true;
            this.label4.ShadowStyle = Terminal.Gui.ShadowStyle.None;
            this.label4.Data = "label4";
            this.label4.Text = "Single:";
            this.label4.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.label4);
            this.numericUpDown3.Width = Dim.Auto();
            this.numericUpDown3.Height = Dim.Auto();
            this.numericUpDown3.X = 8;
            this.numericUpDown3.Y = 7;
            this.numericUpDown3.Visible = true;
            this.numericUpDown3.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.numericUpDown3.CanFocus = true;
            this.numericUpDown3.ShadowStyle = Terminal.Gui.ShadowStyle.None;
            this.numericUpDown3.Data = "numericUpDown3";
            this.numericUpDown3.TextAlignment = Terminal.Gui.Alignment.Start;
            this.numericUpDown3.Value = float.PositiveInfinity;
            this.numericUpDown3.Increment = 1F;
            this.Add(this.numericUpDown3);
            this.label5.Width = Dim.Auto();
            this.label5.Height = 1;
            this.label5.X = 12;
            this.label5.Y = 7;
            this.label5.Visible = true;
            this.label5.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.label5.CanFocus = true;
            this.label5.ShadowStyle = Terminal.Gui.ShadowStyle.None;
            this.label5.Data = "label5";
            this.label5.Text = "(Supports infinitiy!?)";
            this.label5.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.label5);
        }
    }
}
