
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v2.0.2.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace Showcase {
    using System;
    using Terminal.Gui;
    using Terminal.Gui.App;
    using Terminal.Gui.Drawing;
    using Terminal.Gui.Input;
    using Terminal.Gui.ViewBase;
    using Terminal.Gui.Views;
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Drawing;
    
    
    public partial class Ranges : Terminal.Gui.Views.Dialog {
        
        private Terminal.Gui.Views.LinearRange<bool> linearRange1;
        
        private Terminal.Gui.Views.Label label;
        
        private Terminal.Gui.Views.LinearRange<double> linearRange2;
        
        private Terminal.Gui.Views.LinearRange<double> linearRange5;
        
        private Terminal.Gui.Views.Label label2;
        
        private Terminal.Gui.Views.Label label4;
        
        private Terminal.Gui.Views.LinearRange<double> linearRange3;
        
        private Terminal.Gui.Views.Label label3;
        
        private Terminal.Gui.Views.LinearRange<int> linearRange4;
        
        private Terminal.Gui.Views.Label label5;
        
        private Terminal.Gui.Views.Label label7;
        
        private Terminal.Gui.Views.LinearRange<string> linearRange6;
        
        private Terminal.Gui.Views.Label label6;
        
        private Terminal.Gui.Views.LinearRange<string> linearRange7;
        
        private Terminal.Gui.Views.Label label8;
        
        private Terminal.Gui.Views.Label label93;
        
        private Terminal.Gui.Views.Label label9;
        
        private Terminal.Gui.Views.Label label92;
        
        private void InitializeComponent() {
            this.label92 = new Terminal.Gui.Views.Label();
            this.label9 = new Terminal.Gui.Views.Label();
            this.label93 = new Terminal.Gui.Views.Label();
            this.label8 = new Terminal.Gui.Views.Label();
            this.linearRange7 = new Terminal.Gui.Views.LinearRange<string>();
            this.label6 = new Terminal.Gui.Views.Label();
            this.linearRange6 = new Terminal.Gui.Views.LinearRange<string>();
            this.label7 = new Terminal.Gui.Views.Label();
            this.label5 = new Terminal.Gui.Views.Label();
            this.linearRange4 = new Terminal.Gui.Views.LinearRange<int>();
            this.label3 = new Terminal.Gui.Views.Label();
            this.linearRange3 = new Terminal.Gui.Views.LinearRange<double>();
            this.label4 = new Terminal.Gui.Views.Label();
            this.label2 = new Terminal.Gui.Views.Label();
            this.linearRange5 = new Terminal.Gui.Views.LinearRange<double>();
            this.linearRange2 = new Terminal.Gui.Views.LinearRange<double>();
            this.label = new Terminal.Gui.Views.Label();
            this.linearRange1 = new Terminal.Gui.Views.LinearRange<bool>();
            this.Width = Dim.Percent(90);
            this.Height = Dim.Percent(80);
            this.X = Pos.Center();
            this.Y = Pos.Center();
            this.Visible = true;
            this.CanFocus = true;
            this.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyles.Transparent;
            this.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.linearRange1.Width = 15;
            this.linearRange1.Height = 2;
            this.linearRange1.X = 3;
            this.linearRange1.Y = 0;
            this.linearRange1.Visible = true;
            this.linearRange1.CanFocus = true;
            this.linearRange1.ShadowStyle = null;
            this.linearRange1.Options = new System.Collections.Generic.List<Terminal.Gui.Views.LinearRangeOption<bool>>(new Terminal.Gui.Views.LinearRangeOption<bool>[] {
                        new Terminal.Gui.Views.LinearRangeOption<bool>("True", new System.Text.Rune('T'), true),
                        new Terminal.Gui.Views.LinearRangeOption<bool>("False", new System.Text.Rune('F'), false)});
            this.linearRange1.Orientation = Terminal.Gui.ViewBase.Orientation.Horizontal;
            this.linearRange1.RangeAllowSingle = false;
            this.linearRange1.AllowEmpty = false;
            this.linearRange1.MinimumInnerSpacing = 1;
            this.linearRange1.LegendsOrientation = Terminal.Gui.ViewBase.Orientation.Horizontal;
            this.linearRange1.ShowLegends = true;
            this.linearRange1.ShowEndSpacing = false;
            this.linearRange1.Type = Terminal.Gui.Views.LinearRangeType.Single;
            this.linearRange1.Data = "linearRange1";
            this.linearRange1.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Add(this.linearRange1);
            this.label.Width = Dim.Auto();
            this.label.Height = Dim.Auto();
            this.label.X = 59;
            this.label.Y = 0;
            this.label.Visible = true;
            this.label.CanFocus = false;
            this.label.ShadowStyle = null;
            this.label.Data = "label";
            this.label.Text = "LinearRange<bool>";
            this.label.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Add(this.label);
            this.linearRange2.Width = 18;
            this.linearRange2.Height = 2;
            this.linearRange2.X = 3;
            this.linearRange2.Y = 3;
            this.linearRange2.Visible = true;
            this.linearRange2.CanFocus = true;
            this.linearRange2.ShadowStyle = null;
            this.linearRange2.Options = new System.Collections.Generic.List<Terminal.Gui.Views.LinearRangeOption<double>>(new Terminal.Gui.Views.LinearRangeOption<double>[] {
                        new Terminal.Gui.Views.LinearRangeOption<double>("Low", new System.Text.Rune('L'), 0D),
                        new Terminal.Gui.Views.LinearRangeOption<double>("Mid", new System.Text.Rune('M'), 0.5D),
                        new Terminal.Gui.Views.LinearRangeOption<double>("High", new System.Text.Rune('H'), 1D)});
            this.linearRange2.Orientation = Terminal.Gui.ViewBase.Orientation.Horizontal;
            this.linearRange2.RangeAllowSingle = false;
            this.linearRange2.AllowEmpty = false;
            this.linearRange2.MinimumInnerSpacing = 1;
            this.linearRange2.LegendsOrientation = Terminal.Gui.ViewBase.Orientation.Horizontal;
            this.linearRange2.ShowLegends = true;
            this.linearRange2.ShowEndSpacing = false;
            this.linearRange2.Type = Terminal.Gui.Views.LinearRangeType.Single;
            this.linearRange2.Data = "linearRange2";
            this.linearRange2.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Add(this.linearRange2);
            this.linearRange5.Width = 18;
            this.linearRange5.Height = 2;
            this.linearRange5.X = 3;
            this.linearRange5.Y = 3;
            this.linearRange5.Visible = true;
            this.linearRange5.CanFocus = true;
            this.linearRange5.ShadowStyle = null;
            this.linearRange5.Options = new System.Collections.Generic.List<Terminal.Gui.Views.LinearRangeOption<double>>(new Terminal.Gui.Views.LinearRangeOption<double>[] {
                        new Terminal.Gui.Views.LinearRangeOption<double>("Low", new System.Text.Rune('L'), 0D),
                        new Terminal.Gui.Views.LinearRangeOption<double>("Mid", new System.Text.Rune('M'), 0.5D),
                        new Terminal.Gui.Views.LinearRangeOption<double>("High", new System.Text.Rune('H'), 1D)});
            this.linearRange5.Orientation = Terminal.Gui.ViewBase.Orientation.Horizontal;
            this.linearRange5.RangeAllowSingle = false;
            this.linearRange5.AllowEmpty = false;
            this.linearRange5.MinimumInnerSpacing = 1;
            this.linearRange5.LegendsOrientation = Terminal.Gui.ViewBase.Orientation.Horizontal;
            this.linearRange5.ShowLegends = true;
            this.linearRange5.ShowEndSpacing = false;
            this.linearRange5.Type = Terminal.Gui.Views.LinearRangeType.Single;
            this.linearRange5.Data = "linearRange5";
            this.linearRange5.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Add(this.linearRange5);
            this.label2.Width = Dim.Auto();
            this.label2.Height = Dim.Auto();
            this.label2.X = 60;
            this.label2.Y = 3;
            this.label2.Visible = true;
            this.label2.CanFocus = false;
            this.label2.ShadowStyle = null;
            this.label2.Data = "label2";
            this.label2.Text = "LinearRange<double>\r\n(Text Labels)";
            this.label2.TextAlignment = Terminal.Gui.ViewBase.Alignment.Center;
            this.Add(this.label2);
            this.label4.Width = Dim.Auto();
            this.label4.Height = Dim.Auto();
            this.label4.X = 60;
            this.label4.Y = 3;
            this.label4.Visible = true;
            this.label4.CanFocus = false;
            this.label4.ShadowStyle = null;
            this.label4.Data = "label4";
            this.label4.Text = "LinearRange<double>\r\n(Text Labels)";
            this.label4.TextAlignment = Terminal.Gui.ViewBase.Alignment.Center;
            this.Add(this.label4);
            this.linearRange3.Width = 51;
            this.linearRange3.Height = 2;
            this.linearRange3.X = 3;
            this.linearRange3.Y = 6;
            this.linearRange3.Visible = true;
            this.linearRange3.CanFocus = true;
            this.linearRange3.ShadowStyle = null;
            this.linearRange3.Options = new System.Collections.Generic.List<Terminal.Gui.Views.LinearRangeOption<double>>(new Terminal.Gui.Views.LinearRangeOption<double>[] {
                        new Terminal.Gui.Views.LinearRangeOption<double>("0", new System.Text.Rune('0'), 0D),
                        new Terminal.Gui.Views.LinearRangeOption<double>("0.1", new System.Text.Rune('0'), 0.1D),
                        new Terminal.Gui.Views.LinearRangeOption<double>("0.2", new System.Text.Rune('0'), 0.2D),
                        new Terminal.Gui.Views.LinearRangeOption<double>("0.3", new System.Text.Rune('0'), 0.3D),
                        new Terminal.Gui.Views.LinearRangeOption<double>("0.4", new System.Text.Rune('0'), 0.4D),
                        new Terminal.Gui.Views.LinearRangeOption<double>("0.5", new System.Text.Rune('0'), 0.5D),
                        new Terminal.Gui.Views.LinearRangeOption<double>("0.6", new System.Text.Rune('0'), 0.6D),
                        new Terminal.Gui.Views.LinearRangeOption<double>("0.7", new System.Text.Rune('0'), 0.7D),
                        new Terminal.Gui.Views.LinearRangeOption<double>("0.8", new System.Text.Rune('0'), 0.8D),
                        new Terminal.Gui.Views.LinearRangeOption<double>("0.9", new System.Text.Rune('0'), 0.9D),
                        new Terminal.Gui.Views.LinearRangeOption<double>("1", new System.Text.Rune('1'), 1D)});
            this.linearRange3.Orientation = Terminal.Gui.ViewBase.Orientation.Horizontal;
            this.linearRange3.RangeAllowSingle = false;
            this.linearRange3.AllowEmpty = false;
            this.linearRange3.MinimumInnerSpacing = 1;
            this.linearRange3.LegendsOrientation = Terminal.Gui.ViewBase.Orientation.Horizontal;
            this.linearRange3.ShowLegends = true;
            this.linearRange3.ShowEndSpacing = false;
            this.linearRange3.Type = Terminal.Gui.Views.LinearRangeType.Single;
            this.linearRange3.Data = "linearRange3";
            this.linearRange3.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Add(this.linearRange3);
            this.label3.Width = Dim.Auto();
            this.label3.Height = Dim.Auto();
            this.label3.X = 60;
            this.label3.Y = 6;
            this.label3.Visible = true;
            this.label3.CanFocus = false;
            this.label3.ShadowStyle = null;
            this.label3.Data = "label3";
            this.label3.Text = "LinearRange<double>\r\n(Decimal Labels)";
            this.label3.TextAlignment = Terminal.Gui.ViewBase.Alignment.Center;
            this.Add(this.label3);
            this.linearRange4.Width = 52;
            this.linearRange4.Height = 2;
            this.linearRange4.X = 3;
            this.linearRange4.Y = 9;
            this.linearRange4.Visible = true;
            this.linearRange4.CanFocus = true;
            this.linearRange4.ShadowStyle = null;
            this.linearRange4.Options = new System.Collections.Generic.List<Terminal.Gui.Views.LinearRangeOption<int>>(new Terminal.Gui.Views.LinearRangeOption<int>[] {
                        new Terminal.Gui.Views.LinearRangeOption<int>("One", new System.Text.Rune('1'), 1),
                        new Terminal.Gui.Views.LinearRangeOption<int>("Two", new System.Text.Rune('2'), 2),
                        new Terminal.Gui.Views.LinearRangeOption<int>("Three", new System.Text.Rune('3'), 3)});
            this.linearRange4.Orientation = Terminal.Gui.ViewBase.Orientation.Horizontal;
            this.linearRange4.RangeAllowSingle = false;
            this.linearRange4.AllowEmpty = false;
            this.linearRange4.MinimumInnerSpacing = 1;
            this.linearRange4.LegendsOrientation = Terminal.Gui.ViewBase.Orientation.Horizontal;
            this.linearRange4.ShowLegends = true;
            this.linearRange4.ShowEndSpacing = false;
            this.linearRange4.Type = Terminal.Gui.Views.LinearRangeType.Single;
            this.linearRange4.Data = "linearRange4";
            this.linearRange4.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Add(this.linearRange4);
            this.label5.Width = Dim.Auto();
            this.label5.Height = Dim.Auto();
            this.label5.X = 60;
            this.label5.Y = 9;
            this.label5.Visible = true;
            this.label5.CanFocus = false;
            this.label5.ShadowStyle = null;
            this.label5.Data = "label5";
            this.label5.Text = "LinearRange<int>\r\n(Text Labels)";
            this.label5.TextAlignment = Terminal.Gui.ViewBase.Alignment.Center;
            this.Add(this.label5);
            this.label7.Width = Dim.Auto();
            this.label7.Height = Dim.Auto();
            this.label7.X = 60;
            this.label7.Y = 9;
            this.label7.Visible = true;
            this.label7.CanFocus = false;
            this.label7.ShadowStyle = null;
            this.label7.Data = "label7";
            this.label7.Text = "LinearRange<int>\r\n(Text Labels)";
            this.label7.TextAlignment = Terminal.Gui.ViewBase.Alignment.Center;
            this.Add(this.label7);
            this.linearRange6.Width = 25;
            this.linearRange6.Height = 2;
            this.linearRange6.X = 3;
            this.linearRange6.Y = 12;
            this.linearRange6.Visible = true;
            this.linearRange6.CanFocus = true;
            this.linearRange6.ShadowStyle = null;
            this.linearRange6.Options = new System.Collections.Generic.List<Terminal.Gui.Views.LinearRangeOption<string>>(new Terminal.Gui.Views.LinearRangeOption<string>[] {
                        new Terminal.Gui.Views.LinearRangeOption<string>("Cat", new System.Text.Rune('\uD83D'), "Cat"),
                        new Terminal.Gui.Views.LinearRangeOption<string>("Dog", new System.Text.Rune('\uD83D'), "Dog"),
                        new Terminal.Gui.Views.LinearRangeOption<string>("Fish", new System.Text.Rune('\uD83D'), "Fish")});
            this.linearRange6.Orientation = Terminal.Gui.ViewBase.Orientation.Horizontal;
            this.linearRange6.RangeAllowSingle = false;
            this.linearRange6.AllowEmpty = false;
            this.linearRange6.MinimumInnerSpacing = 1;
            this.linearRange6.LegendsOrientation = Terminal.Gui.ViewBase.Orientation.Horizontal;
            this.linearRange6.ShowLegends = true;
            this.linearRange6.ShowEndSpacing = false;
            this.linearRange6.Type = Terminal.Gui.Views.LinearRangeType.Single;
            this.linearRange6.Data = "linearRange6";
            this.linearRange6.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Add(this.linearRange6);
            this.label6.Width = Dim.Auto();
            this.label6.Height = Dim.Auto();
            this.label6.X = 60;
            this.label6.Y = 12;
            this.label6.Visible = true;
            this.label6.CanFocus = false;
            this.label6.ShadowStyle = null;
            this.label6.Data = "label6";
            this.label6.Text = "LinearRange<string>\r\n(Wide)";
            this.label6.TextAlignment = Terminal.Gui.ViewBase.Alignment.Center;
            this.Add(this.label6);
            this.linearRange7.Width = 9;
            this.linearRange7.Height = 2;
            this.linearRange7.X = 3;
            this.linearRange7.Y = 15;
            this.linearRange7.Visible = true;
            this.linearRange7.CanFocus = true;
            this.linearRange7.ShadowStyle = null;
            this.linearRange7.Options = new System.Collections.Generic.List<Terminal.Gui.Views.LinearRangeOption<string>>(new Terminal.Gui.Views.LinearRangeOption<string>[] {
                        new Terminal.Gui.Views.LinearRangeOption<string>("Cat", new System.Text.Rune('\uD83D'), "Cat"),
                        new Terminal.Gui.Views.LinearRangeOption<string>("Dog", new System.Text.Rune('\uD83D'), "Dog"),
                        new Terminal.Gui.Views.LinearRangeOption<string>("Fish", new System.Text.Rune('\uD83D'), "Fish")});
            this.linearRange7.Orientation = Terminal.Gui.ViewBase.Orientation.Horizontal;
            this.linearRange7.RangeAllowSingle = false;
            this.linearRange7.AllowEmpty = false;
            this.linearRange7.MinimumInnerSpacing = 1;
            this.linearRange7.LegendsOrientation = Terminal.Gui.ViewBase.Orientation.Horizontal;
            this.linearRange7.ShowLegends = true;
            this.linearRange7.ShowEndSpacing = false;
            this.linearRange7.Type = Terminal.Gui.Views.LinearRangeType.Single;
            this.linearRange7.Data = "linearRange7";
            this.linearRange7.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Add(this.linearRange7);
            this.label8.Width = Dim.Auto();
            this.label8.Height = Dim.Auto();
            this.label8.X = 60;
            this.label8.Y = 15;
            this.label8.Visible = true;
            this.label8.CanFocus = false;
            this.label8.ShadowStyle = null;
            this.label8.Data = "label8";
            this.label8.Text = "LinearRange<string>\r\n(Thin)";
            this.label8.TextAlignment = Terminal.Gui.ViewBase.Alignment.Center;
            this.Add(this.label8);
            this.label93.Width = Dim.Fill(0);
            this.label93.Height = 1;
            this.label93.X = 0;
            this.label93.Y = Pos.AnchorEnd(3);
            this.label93.Visible = true;
            this.label93.CanFocus = false;
            this.label93.ShadowStyle = null;
            this.label93.Data = "label93";
            this.label93.Text = "--Linear Range Showcase--";
            this.label93.TextAlignment = Terminal.Gui.ViewBase.Alignment.Center;
            this.Add(this.label93);
            this.label9.Width = Dim.Fill(0);
            this.label9.Height = 1;
            this.label9.X = 0;
            this.label9.Y = Pos.AnchorEnd(2);
            this.label9.Visible = true;
            this.label9.CanFocus = false;
            this.label9.ShadowStyle = null;
            this.label9.Data = "label9";
            this.label9.Text = ("LinearRange is a generic class Typed on value. Use \'Options\' to set the radio val" +
                "ues");
            this.label9.TextAlignment = Terminal.Gui.ViewBase.Alignment.Center;
            this.Add(this.label9);
            this.label92.Width = Dim.Fill(0);
            this.label92.Height = 1;
            this.label92.X = 0;
            this.label92.Y = Pos.AnchorEnd(1);
            this.label92.Visible = true;
            this.label92.CanFocus = false;
            this.label92.ShadowStyle = null;
            this.label92.Data = "label92";
            this.label92.Text = "When there is not enough space the \'LegendAbbr\' is used";
            this.label92.TextAlignment = Terminal.Gui.ViewBase.Alignment.Center;
            this.Add(this.label92);
        }
    }
}
