
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v2.0.2.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace Showcase {
    using System;
    using Terminal.Gui;
    using Terminal.Gui.App;
    using Terminal.Gui.Drawing;
    using Terminal.Gui.Input;
    using Terminal.Gui.ViewBase;
    using Terminal.Gui.Views;
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Drawing;
    
    
    public partial class Text : Terminal.Gui.Views.Dialog {
        
        private Terminal.Gui.Views.Label lblTextField;
        
        private Terminal.Gui.Views.TextField textField;
        
        private void InitializeComponent() {
            this.textField = new Terminal.Gui.Views.TextField();
            this.lblTextField = new Terminal.Gui.Views.Label();
            this.Width = Dim.Percent(90);
            this.Height = Dim.Percent(80);
            this.X = Pos.Center();
            this.Y = Pos.Center();
            this.Visible = true;
            this.CanFocus = true;
            this.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyles.Transparent;
            this.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.lblTextField.Width = Dim.Auto();
            this.lblTextField.Height = Dim.Auto();
            this.lblTextField.X = 0;
            this.lblTextField.Y = 0;
            this.lblTextField.Visible = true;
            this.lblTextField.CanFocus = false;
            this.lblTextField.ShadowStyle = null;
            this.lblTextField.Data = "lblTextField";
            this.lblTextField.Text = "TextField:";
            this.lblTextField.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Add(this.lblTextField);
            this.textField.Width = 10;
            this.textField.Height = 1;
            this.textField.X = Pos.Right(lblTextField) + 1;
            this.textField.Y = Pos.Top(lblTextField);
            this.textField.Visible = true;
            this.textField.CanFocus = true;
            this.textField.ShadowStyle = null;
            this.textField.Secret = false;
            this.textField.Data = "textField";
            this.textField.Text = "";
            this.textField.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Add(this.textField);
        }
    }
}
