//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TerminalGuiDesigner {
    using System;
    using Terminal.Gui;
    
    
    public partial class MyWindow {
        
        private Terminal.Gui.Label label2;
        
        private Terminal.Gui.Label label1;
        
        private void InitializeComponent() {
            this.label2 = new Terminal.Gui.Label();
            this.label2.Text = "Heya";
            this.label2.X = 15;
            this.label2.Y = 3;
            this.label2.Data = "label2";
            this.Add(this.label2);
            this.label1 = new Terminal.Gui.Label();
            this.label1.Text = "Heya";
            this.label1.X = 0;
            this.label1.Y = Pos.Bottom(label2) + 1;
            this.label1.Data = "label1";
            this.Add(this.label1);
        }
    }
}
