//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YourNamespace {
    using System;
    using Terminal.Gui;
    
    
    public partial class MyWindow {
        
        private Terminal.Gui.Label label1;
        
        private Terminal.Gui.Label label2;
        
        private void InitializeComponent() {
            this.label1 = new Terminal.Gui.Label();
            this.label1.Data = "label1";
            this.label1.Text = "Hello World";
            this.label1.Width = 11;
            this.label1.Height = 1;
            this.label1.X = 0;
            this.label1.Y = 0;
            this.Add(this.label1);
            this.label2 = new Terminal.Gui.Label();
            this.label2.Data = "label2";
            this.label2.Text = "Heya";
            this.label2.Width = 4;
            this.label2.Height = 1;
            this.label2.X = Pos.Percent(25) + 4;
            this.label2.Y = 0;
            this.Add(this.label2);
        }
    }
}
